/* ============================================
   SHAYNA JUCKER – LANGUAGE SWITCHER
   DE (default) / EN
   ============================================ */

window.SJ_LANG = {
  de: {
    /* --- Index --- */
    'index.tagline':     'Event · Campaigns · Content · Projektmanagement',
    'index.bio':         'Ich bin Shayna – ich plane und inszeniere Brand Experiences, die Menschen bewegen. Nach 2+ Jahren bei Titbit mit Projekten für Migros suche ich eine strategischere Marketingrolle in Zürich, wo ich Kampagnen, Events und Markenauftritte von A bis Z verantworte.',
    'index.bio-p1':      'Brand- und Event-Managerin mit einer Leidenschaft dafür, Erlebnisse zu schaffen, die Menschen mit Marken verbinden. Mit Sitz in Zürich spezialisiere ich mich auf die Leitung grossangelegter Live-Aktivierungen und Markenkampagnen für bedeutende Schweizer Kunden – darunter der Auftritt von Migros an über 10 der ikonischsten Musikfestivals der Schweiz.',
    'index.bio-p2':      'Mit einem Hintergrund in Multimedia-Produktion, Design und strategischer Kommunikation bringe ich sowohl kreative Vision als auch operative Präzision in jedes Projekt – vom ersten Briefing bis zur finalen Umsetzung. Ich leite funktionsübergreifende Teams, betreue Kundenbeziehungen von A bis Z und übernehme die volle Verantwortung für die Ergebnisse.',
    'index.bio-p3':      'Getrieben von einer Leidenschaft für Marken, die inspirieren und Menschen bewegen.',
    'index.thesis':      'Meine Bachelorthesis: Brand Activism & Gen Z – wie Sportmarken Haltung zeigen →',
    'index.contact-cta': 'Du suchst jemanden für Brand Experience oder Marketing?',
    'index.btn-mail':    'Schreib mir',

    /* --- About --- */
    'about.role':            'Brand Experience &amp; Marketing',
    'about.desc':            'Brand- und Event-Managerin mit einer Leidenschaft dafür, Erlebnisse zu schaffen, die Menschen mit Marken verbinden. Mit Sitz in Zürich spezialisiere ich mich auf die Leitung grossangelegter Live-Aktivierungen und Markenkampagnen für bedeutende Schweizer Kunden – darunter der Auftritt von Migros an über 10 der ikonischsten Musikfestivals der Schweiz.',
    'about.desc2':           'Mit einem Hintergrund in Multimedia-Produktion, Design und strategischer Kommunikation bringe ich sowohl kreative Vision als auch operative Präzision in jedes Projekt – vom ersten Briefing bis zur finalen Umsetzung. Ich leite funktionsübergreifende Teams, betreue Kundenbeziehungen von A bis Z und übernehme die volle Verantwortung für die Ergebnisse.',
    'about.desc3':           'Getrieben von einer Leidenschaft für Marken, die inspirieren und Menschen bewegen.',
    'about.exp-heading':     'Erfahrung',
    'about.exp-sub':         'Berufliche Tätigkeiten',
    'about.edu-heading':     'Ausbildung',
    'about.edu-sub':         'Schulische Ausbildung',
    'about.int-heading':     'Interessen',
    'about.int-sub':         'Hobbys & Aktivitäten',
    'about.int-text':        'Eiskunstlauf | Surfen | Snowboard | Ski | Fussball | Sport allgemein | Reisen | Musik | Gitarre spielen | Fotografie | Bildbearbeitung | Grafik | Design | Genauigkeit | Zeit mit Familie & Freunden',

    /* --- Portfolio nav --- */
    'portfolio.design-group': 'Design & Studium',

    /* --- Marketing Cases --- */
    'mkt.tag1':           'Case Study 01',
    'mkt.title1':         'Migros – Schweizweite Festival-Experience 2023/24',
    'mkt.label.context':  'Ausgangslage',
    'mkt.label.role':     'Meine Rolle',
    'mkt.label.actions':  'Was ich gemacht habe',
    'mkt.label.result':   'Ergebnis',
    'mkt.label.learning': 'Was ich gelernt habe',
    'mkt.context1':       'Migros wollte an Schweizer Festivals präsent sein und junge Zielgruppen ansprechen. Titbit wurde beauftragt, Brand Activations zu entwickeln und umzusetzen – von der Konzeption bis zur Durchführung vor Ort.',
    'mkt.role1':          'Ich war verantwortlich für Projektplanung, Kundenabstimmungen mit Migros, Offertenerstellung, Koordination der Lieferanten und operative Durchführung vor Ort.',
    'mkt.action1.1':      'Konzept und Offerte für mehrere Festivaleinsätze erstellt',
    'mkt.action1.2':      'Wöchentliche Abstimmungsmeetings mit Migros-Ansprechperson geleitet',
    'mkt.action1.3':      'Content- und Social-Media-Begleitung der Events koordiniert',
    'mkt.action1.4':      'Aufbau, Durchführung und Abbau vor Ort geleitet',
    'mkt.action1.5':      'Nachbericht mit KPIs für Migros erstellt',
    'mkt.result1':        'Alle Festivaleinsätze erfolgreich durchgeführt. Migros-Kundschaft verlängerte die Zusammenarbeit für das Folgejahr. Positives Feedback auf den begleitenden Social-Media-Content.',
    'mkt.learning1':      'Wie wichtig klare Briefings und frühzeitige Kundenabstimmung sind – besonders wenn kurzfristige Änderungen vor Ort unvermeidlich sind.',
    'mkt.tag2':           'Case Study 02',
    'mkt.title2':         'Multimedia Award 2023 – Tonight Show Live Event',
    'mkt.context2':       'Für den Schweizer Multimedia Award sollte eine Live-Event-Show im Plaza Klub Zürich produziert werden – von der Konzeption bis zur Durchführung.',
    'mkt.role2':          'Ich habe das Showkonzept entwickelt, die Moderation übernommen, Regie geführt, die Kommunikation koordiniert und die technische Produktion geleitet.',
    'mkt.action2.1':      'Showkonzept und Ablaufplan entwickelt',
    'mkt.action2.2':      'Technische Anforderungen mit der Venue koordiniert',
    'mkt.action2.3':      'Moderation und Regie während der Live-Show übernommen',
    'mkt.action2.4':      'Kommunikation und Social Media rund um den Event betreut',
    'mkt.result2':        'Erfolgreiche Durchführung der Live-Show mit Publikum. Mediale Berichterstattung auf multimedia-award.ch.',
    'mkt.cta':            'Interesse an meiner Arbeit?',
    'mkt.btn-mail':       'Schreib mir',

    /* --- ON --- */
    'on.heading':      'Motivationsschreiben',
    'on.salutation':   'Liebes ON-Team',
    'on.p1':           'ON ignites the human spirit through movement. Meine Arbeit beginnt dort, wo eine Marke aufh&ouml;rt zu reden und anf&auml;ngt zu wirken.',
    'on.p2':           'Ich bringe nicht nur Erfahrung mit, sondern auch eine fundierte Perspektive auf ON als Brand. In meiner Bachelorarbeit habe ich die Brand-Activism-Kommunikationsstrategien von ON, Nike und Adidas wissenschaftlich analysiert und dabei verstanden, was ON von anderen unterscheidet: Authentizit&auml;t, die in der DNA sitzt, nicht auf der Kampagnenfl&auml;che klebt.',
    'on.p3':           'Was mich an ON reizt, ist genau dieser Anspruch. <em>Ignite the human spirit through movement</em> ersch&ouml;pft sich nicht in einem Messezelt. Er braucht Formate, die etwas ausl&ouml;sen, Experiences, die &uuml;ber den Moment hinausreichen und Menschen wirklich bewegen. Genau das ist der Massstab, an dem ich meine Arbeit messe.',
    'on.p4':           'Bei Tit-Pit habe ich schweizweit Brand Experiences f&uuml;r Marken wie Migros an &uuml;ber 10 Musikfestivals verantwortet &ndash; von der strategischen Konzeption und Offertenerstellung &uuml;ber Kundenabstimmungen bis zur operativen Umsetzung vor Ort. Parallel habe ich Content Marketing und Social-Media-Kommunikation rund um diese Formate geleitet, weil ein Event f&uuml;r mich erst dann wirklich funktioniert, wenn er ausserhalb des Moments weiterlebt und die Marke st&auml;rkt.',
    'on.p5':           'Diese Verbindung aus Campaign Management, Stakeholder-Verantwortung und operativer Pr&auml;zision ist mein Sweet Spot und passt genau auf das, was ON im Brand Experience-Umfeld bewegt.',
    'on.p6':           'Ich bringe Eigenverantwortung, Tempo und eine l&ouml;sungsorientierte Denkweise mit und bin &uuml;berzeugt, dass die st&auml;rksten Erlebnisse entstehen, wenn echte Begeisterung auf strategisches Denken trifft.',
    'on.closing':      'Keep moving,<br>Shayna Jucker',
    'on.lang-german':    'Deutsch',
    'on.lang-english':   'Englisch',
    'on.skills-heading': 'skills',
    'on.skills-sub':     'Sprachen | F&auml;higkeiten | Programme | Architektur',
    'on.cat-languages':  'Sprachen',
    'on.cat-abilities':  'F&auml;higkeiten',
    'on.cat-programs':   'Programme',
    'on.cat-architecture': 'Architektur',
    'on.cert-heading': 'Zertifikate',
    'on.cert-sub':     'ZERTIFIKATE &amp; NOTEN',
    'on.cert-btn':     'Arbeitszeugnisse &amp; Notenausweise',

    /* --- Bachelor --- */
    'bach.thesis-heading': 'Thesis',
    'bach.thesis-sub':     'All about Bachelorthesis',
    'bach.thesis-intro':   'Introduction',
    'bach.thesis-abs':     'Abstract',
    'bach.thesis-text':    'Brand Activism hat sich als Marketingstrategie etabliert, bei der Unternehmen zu gesellschaftlichen Themen Stellung beziehen. In der Sportbranche gewinnt dieses Konzept zunehmend an Bedeutung, insbesondere im Hinblick auf die Generation Z.',
    'bach.proj-heading':   'Projekt',
    'bach.proj-sub':       'All about Bachelorproject',
    'bach.proj-text':      'Im Rahmen des Bachelorprojekts wurde eine umfassende Corporate Identity und ein Corporate Design (CICD) für ein Bauberatungsunternehmen entwickelt.',
    /* --- Tiny Miracles --- */
    'tm.role':         'Promotion Coordinator 100% &middot; Z&uuml;rich Oerlikon',
    'tm.heading':      'Letter of motivation',
    'tm.salutation':   'Liebes Tiny Miracles-Team',
    'tm.p1':           'Wenn 40&rsquo;000 Menschen auf einem Feld stehen und der Abend l&auml;uft, hat Wochen vorher jemand eine Liste gef&uuml;hrt. Diese Rolle kenne ich &ndash; ich hatte sie in den letzten anderthalb Jahren an &uuml;ber zehn Schweizer Musikfestivals.',
    'tm.p2':           'Bei TIT-PIT verantworte ich die Brand Experiences von Migros an Festivals wie <strong>Frauenfeld</strong>, <strong>Pal&eacute;o</strong>, <strong>Gampel</strong>, <strong>Heitere</strong>, <strong>Moon &amp; Stars</strong> und <strong>Summerdays</strong> &ndash; vom Erstbriefing &uuml;ber Offerte und Konzept bis zur Umsetzung vor Ort. Ich koordiniere Teams, halte Timings, betreue Kunden und stehe am Aufbautag um sechs Uhr auf dem Gel&auml;nde. Was in eurem Inserat unter Koordination, Volunteers und Pr&auml;senz an Shows steht, ist f&uuml;r mich Alltag.',
    'tm.p3':           'Der zweite Teil dieser Rolle ist Sprache. Deutsch und Englisch sind bei mir beide Muttersprache &ndash; meine Mutter ist Amerikanerin. Bei TIT-PIT verantworte ich Social-Media-Content und Kundenkommunikation. Medienmitteilungen, Newsletter, Show-Announcements und Presale-Landingpages in beiden Sprachen zu schreiben und sauber zu redigieren, ist f&uuml;r mich kein Zusatz, sondern der Teil der Arbeit, den ich besonders gern mache.',
    'tm.p4':           'Warum Tiny Miracles? Weil hinter TAKK ab Entertainment die Shows stehen, f&uuml;r die sich Leute ein Jahr im Voraus einen Abend freihalten. Ich komme aus der Musik, ich spiele Gitarre, ich stehe seit Jahren an Festivals &ndash; und ich weiss, wie viel unsichtbare Koordination zwischen einem Ank&uuml;ndigungspost und dem Moment liegt, in dem das Licht ausgeht. In diesem Umfeld zu arbeiten ist f&uuml;r mich kein Stellenwechsel, sondern der logische n&auml;chste Schritt.',
    'tm.p5':           'Die Funktion als zentrale Koordinationsstelle zwischen CEO, Promotion Manager und Team liegt mir. Ich arbeite strukturiert, &uuml;bernehme Verantwortung ohne R&uuml;ckfrage-Schleife und bleibe ruhig, wenn zwei Stunden vor T&uuml;r&ouml;ffnung etwas kippt. Feedback nehme ich gerne entgegen &ndash; und gebe es genauso.',
    'tm.p6':           'Ehrlich sein will ich bei einem Punkt: Franz&ouml;sisch bringe ich nicht mit. Alles &Uuml;brige aus eurem Anforderungsprofil bringe ich mit &ndash; und Franz&ouml;sisch w&uuml;rde ich anpacken, wenn die Rolle es verlangt.',
    'tm.closing':      'Ich freue mich darauf, euch kennenzulernen.<br>Shayna Jucker',
    'tm.match-heading':'match',
    'tm.match-sub':    'Euer Inserat, Punkt f&uuml;r Punkt',
    'tm.m1-label':     'Promotion-Kampagnen unterst&uuml;tzen',
    'tm.m1-text':      '10+ Festival-Aktivierungen pro Jahr &ndash; Briefing, Timeline, Follow-up und Koordination externer Partner und Lieferanten.',
    'tm.m2-label':     'Kommunikationsmaterial verfassen',
    'tm.m2-text':      'Social-Media- und Kundenkommunikation bei TIT-PIT. Deutsch und Englisch Muttersprache, beide schriftlich auf Publikationsniveau.',
    'tm.m3-label':     'Volunteers &amp; Activation-Teams',
    'tm.m3-text':      'Einsatzplanung und F&uuml;hrung der Aktivierungs-Crews an Festivals: Schichten, Briefings, Nachschub und Qualit&auml;t vor Ort.',
    'tm.m4-label':     'Pr&auml;senz an Shows',
    'tm.m4-text':      'Jeden Sommer on-site: Aufbau, Betrieb, Abbau bei &uuml;ber zehn Festivals.',
    'tm.m5-label':     'Akkreditierungen &amp; Fotografen',
    'tm.m5-text':      'Erfahrung mit Medienpartnern, Fotografinnen und Fotografen sowie G&auml;stemanagement auf Festivalgel&auml;nden.',
    'tm.m6-label':     'Online-Werbekampagnen',
    'tm.m6-text':      'Content Marketing und Social Ads rund um Festivalauftritte. Adobe Creative Suite, Figma und Canva im t&auml;glichen Einsatz.',
    'tm.m7-label':     'Pr&auml;sentationen &amp; Reports',
    'tm.m7-text':      'Offerten, Konzepte und Post-Event-Reports mit KPIs f&uuml;r Kunden wie Migros. MS Office t&auml;glich im Einsatz.',
    'tm.m8-label':     'Koordinationsstelle im Team',
    'tm.m8-text':      'Bei TIT-PIT Schnittstelle zwischen Kunde, Kreation, Produktion und Crew &ndash; die Rolle, in der Informationen zusammenlaufen.',
    'tm.facts-label':  'Eckdaten',
    'tm.fact1':        'Verf&uuml;gbar per November 2026',
    'tm.fact2':        '100 % &ndash; Wohnort Pf&auml;ffikon ZH, rund 25 Minuten nach Z&uuml;rich Oerlikon',
    'tm.fact3':        'Deutsch und Englisch Muttersprache, Franz&ouml;sisch nicht vorhanden',
    'tm.fact4':        'BSc Multimedia Production FHGR, Vertiefung Live Communication',
    'tm.fact5':        'Bachelorarbeit: Brand Activism bei ON, Nike und Adidas',
    'tm.skills-heading':'skills',
    'tm.skills-sub':   'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'tm.cert-heading': 'documents',
    'tm.cert-sub':     'LEBENSLAUF, ARBEITSZEUGNISSE &amp; NOTENAUSWEISE',
    'tm.cv-btn':       'Lebenslauf',
    'tm.cert-btn':     'Arbeitszeugnisse &amp; Notenausweise',
    'tm.contact-cta':  'Fragen? Ich bin direkt erreichbar.',
    'tm.btn-mail':     'Schreib mir',

    /* --- Hallo (allgemeine Bewerbung) --- */
    'app.heading':     'Hallo.',
    'app.lead':        'Ich baue Markenerlebnisse, die nicht nur am Eventtag funktionieren.',
    'app.p1':          'Ich bin Shayna Jucker, 28, aus Pf&auml;ffikon ZH. Bei TIT-PIT verantworte ich die Brand Experiences von Migros an &uuml;ber zehn Schweizer Musikfestivals &ndash; vom ersten Briefing bis zum letzten Lastwagen, der das Gel&auml;nde verl&auml;sst.',
    'app.p2':          'Angefangen habe ich woanders: f&uuml;nf Jahre Zeichnerin Architektur, danach das Studium Multimedia Production mit Vertiefung Live Communication. Diese Kombination erkl&auml;rt, wie ich arbeite. Ich lese einen Standplan wie eine Zeichnerin, denke die Marke wie eine Strategin und stehe am Aufbautag um sechs Uhr auf dem Platz.',
    'app.p3':          'Diese Seite ist keine Bewerbung auf eine bestimmte Stelle. Sie zeigt, wof&uuml;r man mich holt &ndash; und wie ich arbeite, wenn es eng wird.',
    'app.roles-heading':'roles',
    'app.roles-sub':   'Wof&uuml;r man mich holt',
    'app.label-proof': 'Beleg',
    'app.label-role':  'Meine Rolle',
    'app.label-actions':'Konkret',
    'app.r1-title':    'Brand Experience &amp; Live-Events',
    'app.r1-sub':      'Markenauftritte, die vor Ort funktionieren und danach weiterleben',
    'app.r1-proof':    '10+ Schweizer Grossfestivals pro Jahr f&uuml;r Migros: Frauenfeld, Pal&eacute;o, Gampel, Heitere, Moon &amp; Stars, Stars in Town, Lumnezia, Luzern Live, Seaside, Summerdays und Summerstage.',
    'app.r1-role':     'Project Manager | Marketing, Events &amp; Brand Experience, TIT-PIT GmbH &ndash; mit voller Kundenverantwortung.',
    'app.r1-a1':       'Konzept und Offerte f&uuml;r Aktivierungen, Abstimmung direkt mit dem Kunden',
    'app.r1-a2':       'Lieferanten, Aufbauteams und Crews koordinieren',
    'app.r1-a3':       'Merci Bus Tour zum 100-Jahr-Jubil&auml;um von Migros (2025)',
    'app.r1-a4':       'Leitung der Mocktail Bar Tour 2026',
    'app.r1-a5':       'On-site Projektleitung: Aufbau, Betrieb, Abbau, Qualit&auml;tssicherung',
    'app.r2-title':    'Kampagnen, Content &amp; Kommunikation',
    'app.r2-sub':      'Text, Bild und Kanal so, dass die Marke danach st&auml;rker ist als vorher',
    'app.r2-proof':    'Deutsch und Englisch Muttersprache. Radioreporterin bei Radio S&uuml;dostschweiz, Social Media und Grafik bei TIT-PIT, Multimedia Design bei fliggs mobile.',
    'app.r2-role':     'Verantwortlich f&uuml;r Content, Grafik und Kundenkommunikation &ndash; von der Idee bis zum ver&ouml;ffentlichten Beitrag.',
    'app.r2-a1':       'Social-Media-Content und Redaktionsplanung rund um Live-Formate',
    'app.r2-a2':       'Grafik und Layout mit Adobe Creative Suite, Figma und Canva',
    'app.r2-a3':       'Kundenkommunikation und konsistente Markensprache &uuml;ber alle Touchpoints',
    'app.r2-a4':       'Recherche, Produktion und Moderation im Radio',
    'app.r2-a5':       'Bachelorarbeit &uuml;ber Brand Activism bei ON, Nike und Adidas',
    'app.r3-title':    'Projektleitung &amp; Koordination',
    'app.r3-sub':      'Die Stelle im Team, an der Informationen zusammenlaufen',
    'app.r3-proof':    'Seit 2020 durchgehend in projektverantwortlichen Rollen &ndash; erst in der Architektur, heute im Live-Marketing.',
    'app.r3-role':     'Schnittstelle zwischen Kunde, Kreation, Produktion und Crew. Entscheiden, priorisieren, nachfassen.',
    'app.r3-a1':       'Full Client Ownership vom Briefing bis zum Schlussrapport',
    'app.r3-a2':       'Budgetverantwortung und Offertwesen',
    'app.r3-a3':       'F&uuml;hrung interdisziplin&auml;rer Teams, auch ohne Weisungsbefugnis',
    'app.r3-a4':       'Termin- und Ablaufplanung &uuml;ber mehrere parallele Projekte',
    'app.r3-a5':       'Eigenst&auml;ndige Projektleitung nach 1.5 Jahren &uuml;bertragen bekommen',
    'app.how-heading': 'principles',
    'app.how-sub':     'Wie ich arbeite',
    'app.h1-label':    'Erst verstehen, dann versprechen',
    'app.h1-text':     'Ich sage einem Kunden lieber im Briefing, dass etwas nicht geht, als am Aufbautag. Das kostet einmal Mut und spart dreimal Geld.',
    'app.h2-label':    'Der Event ist nicht das Ziel',
    'app.h2-text':     'Ein Auftritt funktioniert f&uuml;r mich erst, wenn er ausserhalb des Moments weiterlebt. Deshalb denke ich Content von Anfang an mit, nicht als Nachtrag.',
    'app.h3-label':    'Ruhig bleiben ist eine F&auml;higkeit',
    'app.h3-text':     'Zwei Stunden vor T&uuml;r&ouml;ffnung kippt regelm&auml;ssig etwas. Wer dann Priorit&auml;ten setzt statt zu diskutieren, rettet den Abend.',
    'app.h4-label':    'Pl&auml;ne lesen k&ouml;nnen hilft',
    'app.h4-text':     'F&uuml;nf Jahre Architektur bedeuten: Ich sehe an einem Standplan, ob eine Idee gebaut werden kann, bevor sie jemand offeriert.',
    'app.facts-label': 'In Zahlen',
    'app.fact1':       '10+ Schweizer Grossfestivals pro Jahr in eigener Verantwortung',
    'app.fact2':       '2 Muttersprachen: Deutsch und Englisch',
    'app.fact3':       '5 Jahre Architektur: ArchiCAD, Vectorworks, 3D-Visualisierung',
    'app.fact4':       '1 Auslandsemester Transmedia Design in Tilburg, Niederlande',
    'app.fact5':       '100 Jahre Migros: Merci Bus Tour 2025',
    'app.skills-heading':'skills',
    'app.skills-sub':  'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'app.cert-heading':'documents',
    'app.cert-sub':    'LEBENSLAUF, ARBEITSZEUGNISSE &amp; NOTENAUSWEISE',
    'app.cv-btn':      'Lebenslauf',
    'app.cert-btn':    'Arbeitszeugnisse &amp; Notenausweise',
    'app.cases-btn':   'Cases ansehen',
    'app.contact-cta': 'Passt das zu einer Rolle bei euch?',
    'app.btn-mail':    'Schreib mir',
    'app.btn-linkedin':'LinkedIn',

    /* --- Bewerbung (allgemein) --- */
    'bw.role':         'Marketing &middot; Events &middot; Brand Experience',
    'bw.heading':      'Letter of motivation',
    'bw.salutation':   'Liebes Team',
    'bw.p1':           'Wenn 40&rsquo;000 Menschen auf einem Feld stehen und der Abend l&auml;uft, hat Wochen vorher jemand eine Liste gef&uuml;hrt. Diese Rolle kenne ich &ndash; ich hatte sie in den letzten anderthalb Jahren an &uuml;ber zehn Schweizer Musikfestivals.',
    'bw.p2':           'Bei TIT-PIT verantworte ich die Brand Experiences von Migros an Festivals wie <strong>Frauenfeld</strong>, <strong>Pal&eacute;o</strong>, <strong>Gampel</strong>, <strong>Heitere</strong>, <strong>Moon &amp; Stars</strong> und <strong>Summerdays</strong> &ndash; vom Erstbriefing &uuml;ber Offerte und Konzept bis zur Umsetzung vor Ort. Ich koordiniere Teams und Lieferanten, halte Timings und Budgets, betreue Kunden und stehe am Aufbautag um sechs Uhr auf dem Gel&auml;nde. Vom ersten Briefing bis zum letzten Lastwagen, der das Gel&auml;nde verl&auml;sst, liegt das bei mir.',
    'bw.p3':           'Der zweite Teil meiner Arbeit ist Sprache. Deutsch und Englisch sind bei mir beide Muttersprache &ndash; meine Mutter ist Amerikanerin. Bei TIT-PIT verantworte ich Social-Media-Content und Kundenkommunikation. Konzepte und Texte in beiden Sprachen zu schreiben und sauber zu redigieren, ist f&uuml;r mich kein Zusatz, sondern der Teil der Arbeit, den ich besonders gern mache.',
    'bw.p4':           'Angefangen habe ich woanders: f&uuml;nf Jahre Zeichnerin EFZ Fachrichtung Architektur, danach das Studium Multimedia Production mit Vertiefung Live Communication und ein Austauschsemester in den Niederlanden. Diese Kombination erkl&auml;rt, wie ich arbeite. Ich lese einen Standplan wie eine Zeichnerin, denke die Marke wie eine Strategin und behalte beides im Blick, wenn es eng wird.',
    'bw.p5':           'Ich arbeite strukturiert, &uuml;bernehme Verantwortung ohne R&uuml;ckfrage-Schleife und bleibe ruhig, wenn zwei Stunden vor T&uuml;r&ouml;ffnung etwas kippt. Ich sch&auml;tze den direkten Draht ins Team und zu Kundinnen und Kunden. Feedback nehme ich gerne entgegen &ndash; und gebe es genauso.',
    'bw.p6':           'Was ich suche, ist eine Rolle, in der Marke, Event und Kommunikation zusammenlaufen und ich Projekte von A bis Z verantworte &ndash; im Team, mit Kunden, vor Ort. Ob das bei euch Brand Experience, Event, Marketing, Kommunikation oder Projektleitung heisst, ist mir weniger wichtig als die Frage, ob am Ende etwas entsteht, das Menschen bewegt. Genau das mache ich gern, und genau darin bin ich gut.',
    'bw.closing':      'Alles Weitere gerne im Gespr&auml;ch. Ich freue mich darauf, euch kennenzulernen.<br>Shayna Jucker',
    'bw.skills-heading':'skills',
    'bw.skills-sub':   'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'bw.cert-heading': 'documents',
    'bw.cert-sub':     'LEBENSLAUF, ARBEITSZEUGNISSE &amp; NOTENAUSWEISE',
    'bw.cv-btn':       'Lebenslauf',
    'bw.cert-btn':     'Arbeitszeugnisse &amp; Notenausweise',
    'bw.contact-cta':  'Fragen? Ich bin direkt erreichbar.',
    'bw.btn-mail':     'Schreib mir',

    /* --- Arbeitsprobe Presale --- */
    'ps.eyebrow':      'Arbeitsprobe f&uuml;r Tiny Miracles Communication AG',
    'ps.heading':      'Presale-Landingpage',
    'ps.lead':         'Im Inserat steht &laquo;presale landing pages&raquo;. Statt zu schreiben, dass ich das kann, habe ich eine gebaut.',
    'ps.p1':           'Eine Presale-Seite hat genau eine Aufgabe: Zwischen Ank&uuml;ndigung und Verkaufsstart darf keine Frage offen bleiben, die sonst im Info-Postfach landet. Jede Frage, die die Seite beantwortet, ist eine Mail, die niemand beantworten muss.',
    'ps.p2':           'Deshalb ist sie nicht nach Sch&ouml;nheit sortiert, sondern nach der Reihenfolge, in der Leute denken: Wann? Wie komme ich an den Code? Was kostet es? Darf ich rein? Und als Medium: wer ist meine Ansprechperson?',
    'ps.p3':           'Der Countdown kennt vier Zust&auml;nde &ndash; vor dem Presale, w&auml;hrend des Presales, zwischen Presale und freiem Verkauf, danach. Eine Seite, die am Verkaufstag noch &laquo;startet in 0 Tagen&raquo; anzeigt, kostet Vertrauen. Genau solche Details entscheiden, ob eine Ank&uuml;ndigung sauber l&auml;uft oder Support ausl&ouml;st.',
    'ps.p4':           'Technisch ist es eine einzige HTML-Datei: kein Framework, keine Build-Tools, keine externen Requests. F&uuml;r die n&auml;chste Show werden acht Werte getauscht &ndash; Act, Tour, Datum, Venue, drei Verkaufszeitpunkte, Preise. Deutsch und Englisch sind eingebaut.',
    'ps.btn-demo':     'Landingpage &ouml;ffnen',
    'ps.btn-pr':       'Medienmitteilung DE / EN',
    'ps.does-heading': 'details',
    'ps.does-sub':     'Was die Seite leistet',
    'ps.d1-label':     'Alle Termine an einem Ort',
    'ps.d1-text':      'Code-Versand, Presale-Fenster und freier Verkauf stehen mit Datum und Uhrzeit auf der Seite. Das sind die drei Fragen, die sonst einzeln per Mail kommen.',
    'ps.d2-label':     'Vier Countdown-Zust&auml;nde',
    'ps.d2-text':      'Die Seite bleibt korrekt, auch wenn sie am Verkaufstag niemand anfasst. Nach dem Verkaufsstart verschwindet der Z&auml;hler von selbst.',
    'ps.d3-label':     'Zweisprachig ab Werk',
    'ps.d3-text':      'Deutsch und Englisch liegen in derselben Datei, umschaltbar per Klick. Kein zweites Template, keine zweite Pflegestelle.',
    'ps.d4-label':     'Akkreditierung vorweg gekl&auml;rt',
    'ps.d4-text':      'Frist, Regeln im Graben und Ansprechperson stehen direkt auf der Seite. Das nimmt vor jeder Show einen Stapel Einzelanfragen weg.',
    'ps.d5-label':     'Barrierefreiheit und Resale beantwortet',
    'ps.d5-text':      'Rollstuhlpl&auml;tze, Begleitticket und Zweitmarkt sind die zwei Themen, die sonst zuverl&auml;ssig im Postfach landen. Beide sind in der FAQ abgeholt.',
    'ps.d6-label':     'Eine Datei, keine Abh&auml;ngigkeiten',
    'ps.d6-text':      'L&auml;uft auf jedem Hosting, l&auml;dt nichts von aussen nach und ist in etwa zehn Minuten auf die n&auml;chste Show angepasst.',
    'ps.honest-label': 'Ehrlichkeitshalber',
    'ps.honest1':      'Luma Rivers, Nils Bregenz, Datum und Preise sind frei erfunden',
    'ps.honest2':      'Kein offizielles Material eines Veranstalters, kein Bezug zu einer real geplanten Show',
    'ps.honest3':      'Als Pressekontakt steht bewusst meine eigene Adresse',
    'ps.honest4':      'Das Newsletter-Feld ist absichtlich deaktiviert &ndash; eine Arbeitsprobe sammelt keine Adressen',
    'ps.honest5':      'Gebaut am Wochenende, in unter einem Tag',
    'ps.pr-heading':   'press release',
    'ps.pr-sub':       'Show-Announcement zur gleichen Show',
    'ps.pr-text':      'Zur Landingpage geh&ouml;rt die Medienmitteilung, weil in der Praxis beides am selben Morgen rausgeht. Deutsch und Englisch, im &uuml;blichen Aufbau: Sperrfrist, Ort und Datum, Lead mit den W-Fragen, Zitat, Ticketing-Block, Kurzportr&auml;t und Medienkontakt. Das ist gleichzeitig meine Schreibprobe in beiden Sprachen.',
    'ps.btn-pr2':      'Medienmitteilung DE / EN',
    'ps.btn-back':     'Zur Bewerbung',
    'ps.contact-cta':  'Fragen zur Arbeitsprobe? Gerne direkt.',
    'ps.btn-mail':     'Schreib mir',
    'tm.sample-heading':'work sample',
    'tm.sample-sub':   'Statt Behauptung: die Arbeit selbst',
    'tm.sample-text':  'Euer Inserat nennt &laquo;presale landing pages&raquo; als Aufgabe. Ich habe eine gebaut &ndash; mit Countdown &uuml;ber vier Verkaufszust&auml;nde, FAQ, Akkreditierungsregeln, Deutsch und Englisch, als eine einzige Datei ohne Abh&auml;ngigkeiten. Dazu die passende Medienmitteilung in beiden Sprachen. Die Show darin ist frei erfunden, die Mechanik ist echt.',
    'tm.sample-btn':   'Arbeitsprobe ansehen',
  },

  en: {
    /* --- Index --- */
    'index.tagline':     'Events · Campaigns · Content · Project Management',
    'index.bio':         'I\'m Shayna – I plan and stage brand experiences that move people. After 2+ years at Titbit on projects for Migros, I\'m looking for a more strategic marketing role in Zurich, where I can own campaigns, events and brand activations from A to Z.',
    'index.bio-p1':      'Brand and Event Manager with a passion for creating experiences that connect people with brands. Based in Zurich, I specialise in managing large-scale live activations and brand campaigns for major Swiss clients – including Migros\' presence at 10+ of Switzerland\'s most iconic music festivals.',
    'index.bio-p2':      'With a background in multimedia production, design and strategic communication, I bring both creative vision and operational precision to every project – from first briefing to final execution. I lead cross-functional teams, manage client relationships end-to-end and take full ownership of results.',
    'index.bio-p3':      'Driven by a passion for brands that inspire and move people.',
    'index.thesis':      'My Bachelor Thesis: Brand Activism & Gen Z – how sports brands take a stand →',
    'index.contact-cta': 'Looking for someone in Brand Experience or Marketing?',
    'index.btn-mail':    'Write me',

    /* --- About --- */
    'about.role':            'Brand Experience &amp; Marketing',
    'about.desc':            'Brand and event professional with a passion for creating experiences that connect people with brands. Based in Zurich, I specialise in managing large-scale live activations and brand campaigns for major Swiss clients – including Migros\' presence at 10+ of Switzerland\'s most iconic music festivals.',
    'about.desc2':           'With a background in multimedia production, design and strategic communication, I bring both creative vision and operational precision to every project – from first briefing to final execution. I lead cross-functional teams, manage client relationships end-to-end and take full ownership of results.',
    'about.desc3':           'Driven by a passion for brands that inspire and move people.',
    'about.exp-heading':     'Experience',
    'about.exp-sub':         'Occupational activities',
    'about.edu-heading':     'Education',
    'about.edu-sub':         'School education',
    'about.int-heading':     'Interests',
    'about.int-sub':         'Hobbies & Activities',
    'about.int-text':        'Figure Skat | Surf | Snowboard | Ski | Soccer | Sports in General | Travel | Music | Playing Guitar | Photography | Image Editing | Graphics | Design | Attention to Detail | Keeping in touch with Family & Friends',

    /* --- Portfolio nav --- */
    'portfolio.design-group': 'Design & Studies',

    /* --- Marketing Cases --- */
    'mkt.tag1':           'Case Study 01',
    'mkt.title1':         'Migros – Nationwide Festival Experience 2023/24',
    'mkt.label.context':  'Background',
    'mkt.label.role':     'My Role',
    'mkt.label.actions':  'What I Did',
    'mkt.label.result':   'Results',
    'mkt.label.learning': 'What I Learned',
    'mkt.context1':       'Migros wanted to be present at Swiss festivals and reach younger audiences. Titbit was commissioned to develop and execute brand activations – from concept to on-site delivery.',
    'mkt.role1':          'I was responsible for project planning, client coordination with Migros, quote preparation, supplier coordination and operational on-site management.',
    'mkt.action1.1':      'Created concepts and quotes for multiple festival activations',
    'mkt.action1.2':      'Led weekly alignment meetings with the Migros contact',
    'mkt.action1.3':      'Coordinated content and social media coverage of the events',
    'mkt.action1.4':      'Managed on-site setup, execution and teardown',
    'mkt.action1.5':      'Created post-event report with KPIs for Migros',
    'mkt.result1':        'All festival activations successfully delivered. Migros extended the partnership for the following year. Positive feedback on the accompanying social media content.',
    'mkt.learning1':      'How important clear briefings and early client alignment are – especially when last-minute changes on site are unavoidable.',
    'mkt.tag2':           'Case Study 02',
    'mkt.title2':         'Multimedia Award 2023 – Tonight Show Live Event',
    'mkt.context2':       'A live event show at Plaza Klub Zurich was to be produced for the Swiss Multimedia Award – from concept to execution.',
    'mkt.role2':          'I developed the show concept, hosted the event, directed the production, coordinated communications and led the technical production.',
    'mkt.action2.1':      'Developed show concept and run-of-show',
    'mkt.action2.2':      'Coordinated technical requirements with the venue',
    'mkt.action2.3':      'Hosted and directed the live show',
    'mkt.action2.4':      'Managed communications and social media around the event',
    'mkt.result2':        'Successful live show in front of a live audience. Media coverage on multimedia-award.ch.',
    'mkt.cta':            'Interested in my work?',
    'mkt.btn-mail':       'Write me',

    /* --- ON --- */
    'on.heading':      'Letter of Motivation',
    'on.salutation':   'Dear ON Team',
    'on.p1':           'ON ignites the human spirit through movement. My work begins where a brand stops talking and starts making an impact.',
    'on.p2':           'I don\'t just bring experience &ndash; I also bring a well-founded perspective on ON as a brand. In my bachelor\'s thesis, I analysed the brand activism communication strategies of ON, Nike and Adidas, and came to understand what sets ON apart: authenticity that lives in the DNA, not stuck on the campaign surface.',
    'on.p3':           'What draws me to ON is precisely this ambition. <em>Ignite the human spirit through movement</em> doesn\'t exhaust itself in a trade show tent. It demands formats that trigger something, experiences that reach beyond the moment and truly move people. That\'s the standard I hold my own work to.',
    'on.p4':           'At Tit-Pit, I led brand experiences for brands like Migros across 10+ music festivals throughout Switzerland &ndash; from strategic concept and quoting through client alignment to on-site execution. In parallel, I managed content marketing and social media around these formats, because for me an event only truly works when it lives on beyond the moment and strengthens the brand.',
    'on.p5':           'This combination of campaign management, stakeholder ownership and operational precision is my sweet spot &ndash; and a perfect match for what ON does in the brand experience space.',
    'on.p6':           'I bring ownership, pace and a solutions-oriented mindset, and I believe the strongest experiences are created when genuine enthusiasm meets strategic thinking.',
    'on.closing':      'Keep moving,<br>Shayna Jucker',
    'on.lang-german':    'German',
    'on.lang-english':   'English',
    'on.skills-heading': 'skills',
    'on.skills-sub':     'Languages | Abilities | Programs | Architecture',
    'on.cat-languages':  'Languages',
    'on.cat-abilities':  'Abilities',
    'on.cat-programs':   'Programs',
    'on.cat-architecture': 'Architecture',
    'on.cert-heading': 'certificates',
    'on.cert-sub':     'CERTIFICATES &amp; GRADES',
    'on.cert-btn':     'Employment References &amp; Transcripts',

    /* --- Bachelor --- */
    'bach.thesis-heading': 'Thesis',
    'bach.thesis-sub':     'All about Bachelor Thesis',
    'bach.thesis-intro':   'Introduction',
    'bach.thesis-abs':     'Abstract',
    'bach.thesis-text':    'Brand Activism has established itself as a marketing strategy in which companies take a stand on social issues. In the sports industry, this concept is gaining increasing importance, particularly with regard to Generation Z.',
    'bach.proj-heading':   'Project',
    'bach.proj-sub':       'All about Bachelor Project',
    'bach.proj-text':      'As part of the bachelor project, a comprehensive corporate identity and corporate design (CICD) was developed for a construction consulting firm.',
    /* --- Tiny Miracles --- */
    'tm.role':         'Promotion Coordinator 100% &middot; Zurich Oerlikon',
    'tm.heading':      'Letter of Motivation',
    'tm.salutation':   'Dear Tiny Miracles Team',
    'tm.p1':           'When 40,000 people are standing in a field and the evening runs, someone kept a list for weeks beforehand. I know that role &ndash; I have held it at more than ten Swiss music festivals over the past year and a half.',
    'tm.p2':           'At TIT-PIT I am responsible for Migros brand experiences at festivals such as <strong>Frauenfeld</strong>, <strong>Pal&eacute;o</strong>, <strong>Gampel</strong>, <strong>Heitere</strong>, <strong>Moon &amp; Stars</strong> and <strong>Summerdays</strong> &ndash; from the first briefing through quoting and concept to on-site execution. I coordinate teams, hold timings, look after clients and stand on the ground at six in the morning on build day. What your ad lists under coordination, volunteers and presence at shows is my everyday work.',
    'tm.p3':           'The second half of this role is language. German and English are both mother tongues for me &ndash; my mother is American. At TIT-PIT I own social media content and client communication. Writing and editing press releases, newsletters, show announcements and presale landing pages in both languages is not an add-on for me &ndash; it is the part of the work I enjoy most.',
    'tm.p4':           'Why Tiny Miracles? Because behind TAKK ab Entertainment are the shows people keep an evening free for a year in advance. I come from music, I play guitar, I have spent years on festival grounds &ndash; and I know how much invisible coordination sits between an announcement post and the moment the lights go down. Working in that environment is not a job change for me, it is the logical next step.',
    'tm.p5':           'The role as central coordination point between CEO, Promotion Manager and team suits me. I work in a structured way, take ownership without a second loop of questions, and stay calm when something goes sideways two hours before doors. I welcome feedback &ndash; and I give it just as readily.',
    'tm.p6':           'One point where I want to be honest: I do not bring French. Everything else in your requirements profile I do bring &ndash; and I would take French on if the role calls for it.',
    'tm.closing':      'I look forward to meeting you.<br>Shayna Jucker',
    'tm.match-heading':'match',
    'tm.match-sub':    'Your job ad, point by point',
    'tm.m1-label':     'Supporting promotion campaigns',
    'tm.m1-text':      '10+ festival activations per year &ndash; briefings, timelines, follow-ups and coordination with external partners and suppliers.',
    'tm.m2-label':     'Drafting communication materials',
    'tm.m2-text':      'Social media and client communication at TIT-PIT. German and English mother tongue, both at publishing level in writing.',
    'tm.m3-label':     'Volunteers &amp; activation teams',
    'tm.m3-text':      'Scheduling and leading activation crews at festivals: shifts, briefings, resupply and quality on site.',
    'tm.m4-label':     'Presence at shows',
    'tm.m4-text':      'On site every summer: build-up, operation and teardown at more than ten festivals.',
    'tm.m5-label':     'Accreditations &amp; photographers',
    'tm.m5-text':      'Experience with media partners, photographers and guest management on festival grounds.',
    'tm.m6-label':     'Online advertising campaigns',
    'tm.m6-text':      'Content marketing and social ads around festival appearances. Adobe Creative Suite, Figma and Canva in daily use.',
    'tm.m7-label':     'Presentations &amp; reports',
    'tm.m7-text':      'Quotes, concepts and post-event reports with KPIs for clients such as Migros. MS Office in daily use.',
    'tm.m8-label':     'Coordination point in the team',
    'tm.m8-text':      'At TIT-PIT the interface between client, creation, production and crew &ndash; the role where information comes together.',
    'tm.facts-label':  'Key facts',
    'tm.fact1':        'Available from November 2026',
    'tm.fact2':        '100% &ndash; based in Pf&auml;ffikon ZH, about 25 minutes to Zurich Oerlikon',
    'tm.fact3':        'German and English mother tongue, no French',
    'tm.fact4':        'BSc Multimedia Production FHGR, specialisation Live Communication',
    'tm.fact5':        'Bachelor thesis: brand activism at ON, Nike and Adidas',
    'tm.skills-heading':'skills',
    'tm.skills-sub':   'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'tm.cert-heading': 'documents',
    'tm.cert-sub':     'CV, EMPLOYMENT REFERENCES &amp; TRANSCRIPTS',
    'tm.cv-btn':       'Curriculum Vitae',
    'tm.cert-btn':     'Employment References &amp; Transcripts',
    'tm.contact-cta':  'Questions? I am reachable directly.',
    'tm.btn-mail':     'Write me',

    /* --- Hallo (general application) --- */
    'app.heading':     'Hello.',
    'app.lead':        'I build brand experiences that work beyond the day of the event.',
    'app.p1':          'I am Shayna Jucker, 28, based in Pf&auml;ffikon ZH. At TIT-PIT I am responsible for Migros brand experiences at more than ten Swiss music festivals &ndash; from the first briefing to the last truck leaving the ground.',
    'app.p2':          'I started somewhere else: five years as an architectural drafter, then a degree in Multimedia Production with a specialisation in Live Communication. That combination explains how I work. I read a stand plan like a drafter, think the brand like a strategist and stand on site at six in the morning on build day.',
    'app.p3':          'This page is not an application for one specific job. It shows what people hire me for &ndash; and how I work when things get tight.',
    'app.roles-heading':'roles',
    'app.roles-sub':   'What people hire me for',
    'app.label-proof': 'Evidence',
    'app.label-role':  'My Role',
    'app.label-actions':'In practice',
    'app.r1-title':    'Brand Experience &amp; Live Events',
    'app.r1-sub':      'Brand appearances that work on site and live on afterwards',
    'app.r1-proof':    '10+ major Swiss festivals per year for Migros: Frauenfeld, Pal&eacute;o, Gampel, Heitere, Moon &amp; Stars, Stars in Town, Lumnezia, Luzern Live, Seaside, Summerdays and Summerstage.',
    'app.r1-role':     'Project Manager | Marketing, Events &amp; Brand Experience, TIT-PIT GmbH &ndash; with full client ownership.',
    'app.r1-a1':       'Concepts and quotes for activations, aligned directly with the client',
    'app.r1-a2':       'Coordinating suppliers, build teams and crews',
    'app.r1-a3':       'Merci Bus Tour for the 100th anniversary of Migros (2025)',
    'app.r1-a4':       'Lead on the Mocktail Bar Tour 2026',
    'app.r1-a5':       'On-site project leadership: build-up, operation, teardown, quality assurance',
    'app.r2-title':    'Campaigns, Content &amp; Communication',
    'app.r2-sub':      'Copy, image and channel so the brand is stronger afterwards than before',
    'app.r2-proof':    'German and English mother tongue. Radio reporter at Radio S&uuml;dostschweiz, social media and graphic design at TIT-PIT, multimedia design at fliggs mobile.',
    'app.r2-role':     'Responsible for content, design and client communication &ndash; from the idea to the published piece.',
    'app.r2-a1':       'Social media content and editorial planning around live formats',
    'app.r2-a2':       'Design and layout with Adobe Creative Suite, Figma and Canva',
    'app.r2-a3':       'Client communication and a consistent brand voice across all touchpoints',
    'app.r2-a4':       'Research, production and presenting on radio',
    'app.r2-a5':       'Bachelor thesis on brand activism at ON, Nike and Adidas',
    'app.r3-title':    'Project Management &amp; Coordination',
    'app.r3-sub':      'The place in the team where information comes together',
    'app.r3-proof':    'In project ownership roles continuously since 2020 &ndash; first in architecture, today in live marketing.',
    'app.r3-role':     'Interface between client, creation, production and crew. Decide, prioritise, follow up.',
    'app.r3-a1':       'Full client ownership from briefing to final report',
    'app.r3-a2':       'Budget responsibility and quoting',
    'app.r3-a3':       'Leading cross-functional teams, including without formal authority',
    'app.r3-a4':       'Scheduling and sequencing across several parallel projects',
    'app.r3-a5':       'Trusted with independent project leadership within 1.5 years',
    'app.how-heading': 'principles',
    'app.how-sub':     'How I work',
    'app.h1-label':    'Understand first, promise second',
    'app.h1-text':     'I would rather tell a client in the briefing that something will not work than on build day. It takes courage once and saves money three times.',
    'app.h2-label':    'The event is not the goal',
    'app.h2-text':     'An appearance only works for me when it lives on beyond the moment. That is why I plan content in from the start, not as an afterthought.',
    'app.h3-label':    'Staying calm is a skill',
    'app.h3-text':     'Two hours before doors, something regularly goes sideways. Whoever sets priorities then instead of debating saves the evening.',
    'app.h4-label':    'Being able to read plans helps',
    'app.h4-text':     'Five years of architecture mean I can tell from a stand plan whether an idea can be built &ndash; before anyone quotes it.',
    'app.facts-label': 'In numbers',
    'app.fact1':       '10+ major Swiss festivals per year under my own responsibility',
    'app.fact2':       '2 mother tongues: German and English',
    'app.fact3':       '5 years of architecture: ArchiCAD, Vectorworks, 3D visualisation',
    'app.fact4':       '1 semester abroad in Transmedia Design in Tilburg, Netherlands',
    'app.fact5':       '100 years of Migros: Merci Bus Tour 2025',
    'app.skills-heading':'skills',
    'app.skills-sub':  'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'app.cert-heading':'documents',
    'app.cert-sub':    'CV, EMPLOYMENT REFERENCES &amp; TRANSCRIPTS',
    'app.cv-btn':      'Curriculum Vitae',
    'app.cert-btn':    'Employment References &amp; Transcripts',
    'app.cases-btn':   'View cases',
    'app.contact-cta': 'Does this fit a role at your company?',
    'app.btn-mail':    'Write me',
    'app.btn-linkedin':'LinkedIn',

    /* --- General application --- */
    'bw.role':         'Marketing &middot; Events &middot; Brand Experience',
    'bw.heading':      'Letter of Motivation',
    'bw.salutation':   'Dear Team',
    'bw.p1':           'When 40,000 people are standing in a field and the evening runs, someone kept a list for weeks beforehand. I know that role &ndash; I have held it at more than ten Swiss music festivals over the past year and a half.',
    'bw.p2':           'At TIT-PIT I am responsible for Migros brand experiences at festivals such as <strong>Frauenfeld</strong>, <strong>Pal&eacute;o</strong>, <strong>Gampel</strong>, <strong>Heitere</strong>, <strong>Moon &amp; Stars</strong> and <strong>Summerdays</strong> &ndash; from the first briefing through quoting and concept to on-site execution. I coordinate teams and suppliers, hold timings and budgets, look after clients and stand on the ground at six in the morning on build day. From the first briefing to the last truck leaving the site, that is mine.',
    'bw.p3':           'The second half of my work is language. German and English are both mother tongues for me &ndash; my mother is American. At TIT-PIT I own social media content and client communication. Writing and editing concepts and copy in both languages is not an add-on for me &ndash; it is the part of the work I enjoy most.',
    'bw.p4':           'I started somewhere else: five years as a draughtswoman in architecture, then a BSc in Multimedia Production with a specialisation in Live Communication and an exchange semester in the Netherlands. That combination explains how I work. I read a stand layout like a draughtswoman, think about the brand like a strategist, and keep an eye on both when things get tight.',
    'bw.p5':           'I work in a structured way, take ownership without a second loop of questions, and stay calm when something goes sideways two hours before doors. I value a direct line to the team and to clients. I welcome feedback &ndash; and I give it just as readily.',
    'bw.p6':           'What I am looking for is a role where brand, event and communication come together and I own projects from A to Z &ndash; in the team, with clients, on site. Whether you call that brand experience, events, marketing, communication or project management matters less to me than whether something comes out of it that moves people. That is what I love doing, and that is what I am good at.',
    'bw.closing':      'Happy to discuss everything else in person. I look forward to meeting you.<br>Shayna Jucker',
    'bw.skills-heading':'skills',
    'bw.skills-sub':   'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'bw.cert-heading': 'documents',
    'bw.cert-sub':     'CV, EMPLOYMENT REFERENCES &amp; TRANSCRIPTS',
    'bw.cv-btn':       'Curriculum Vitae',
    'bw.cert-btn':     'Employment References &amp; Transcripts',
    'bw.contact-cta':  'Questions? I am directly reachable.',
    'bw.btn-mail':     'Write me',

    /* --- Presale work sample --- */
    'ps.eyebrow':      'Work sample for Tiny Miracles Communication AG',
    'ps.heading':      'Presale Landing Page',
    'ps.lead':         'Your ad says &ldquo;presale landing pages&rdquo;. Instead of writing that I can do it, I built one.',
    'ps.p1':           'A presale page has exactly one job: between the announcement and the on-sale, no question should be left open that would otherwise land in the info inbox. Every question the page answers is an email nobody has to write.',
    'ps.p2':           'So it is not ordered by aesthetics but by the order people think in: When? How do I get the code? What does it cost? Am I allowed in? And, as a journalist: who is my contact?',
    'ps.p3':           'The countdown knows four states &ndash; before the presale, during the presale, between presale and general sale, and after. A page still showing &ldquo;starts in 0 days&rdquo; on sale day costs trust. Details like that decide whether an announcement runs cleanly or generates support.',
    'ps.p4':           'Technically it is a single HTML file: no framework, no build tools, no external requests. For the next show you swap eight values &ndash; act, tour, date, venue, three sale timestamps, prices. German and English are built in.',
    'ps.btn-demo':     'Open the landing page',
    'ps.btn-pr':       'Press release DE / EN',
    'ps.does-heading': 'details',
    'ps.does-sub':     'What the page does',
    'ps.d1-label':     'Every date in one place',
    'ps.d1-text':      'Code send-out, presale window and general sale are on the page with date and time. Those are the three questions that otherwise arrive one by one by email.',
    'ps.d2-label':     'Four countdown states',
    'ps.d2-text':      'The page stays correct even if nobody touches it on sale day. Once tickets are on open sale the counter removes itself.',
    'ps.d3-label':     'Bilingual out of the box',
    'ps.d3-text':      'German and English live in the same file, switchable with one click. No second template, no second thing to maintain.',
    'ps.d4-label':     'Accreditation answered up front',
    'ps.d4-text':      'Deadline, pit rules and contact are on the page. That removes a stack of individual requests before every show.',
    'ps.d5-label':     'Accessibility and resale answered',
    'ps.d5-text':      'Wheelchair spaces, companion tickets and the secondary market are the two topics that reliably reach the inbox. Both are covered in the FAQ.',
    'ps.d6-label':     'One file, no dependencies',
    'ps.d6-text':      'Runs on any hosting, loads nothing from outside and is adapted to the next show in about ten minutes.',
    'ps.honest-label': 'For the record',
    'ps.honest1':      'Luma Rivers, Nils Bregenz, the date and the prices are invented',
    'ps.honest2':      'Not official material from any promoter, no reference to a real planned show',
    'ps.honest3':      'The press contact is deliberately my own address',
    'ps.honest4':      'The newsletter field is intentionally disabled &ndash; a work sample does not collect addresses',
    'ps.honest5':      'Built over a weekend, in under a day',
    'ps.pr-heading':   'press release',
    'ps.pr-sub':       'Show announcement for the same show',
    'ps.pr-text':      'The press release belongs with the landing page because in practice both go out the same morning. German and English, in the usual structure: embargo, dateline, lead answering the basic questions, quote, ticketing block, boilerplate and media contact. It doubles as my writing sample in both languages.',
    'ps.btn-pr2':      'Press release DE / EN',
    'ps.btn-back':     'Back to the application',
    'ps.contact-cta':  'Questions about the work sample? Directly, please.',
    'ps.btn-mail':     'Write me',
    'tm.sample-heading':'work sample',
    'tm.sample-sub':   'Not a claim &ndash; the work itself',
    'tm.sample-text':  'Your ad lists &ldquo;presale landing pages&rdquo; as a task. So I built one &ndash; with a countdown across four sale states, FAQ, accreditation rules, German and English, as a single file with no dependencies. Plus the matching press release in both languages. The show in it is invented; the mechanics are real.',
    'tm.sample-btn':   'See the work sample',
  }
};

(function () {
  var STORAGE_KEY = 'sj_lang';

  function getCurrentLang() {
    return localStorage.getItem(STORAGE_KEY) || 'de';
  }

  function applyLang(lang) {
    var dict = window.SJ_LANG[lang];
    if (!dict) return;

    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (dict[key] !== undefined) {
        el.innerHTML = dict[key];
      }
    });

    /* Update skill-item hover labels */
    document.querySelectorAll('[data-level-de][data-level-en]').forEach(function (el) {
      el.setAttribute('data-level', el.getAttribute('data-level-' + lang));
    });

    /* Update toggle button label */
    var btn = document.getElementById('lang-toggle');
    if (btn) btn.textContent = lang === 'de' ? 'EN' : 'DE';

    /* Update html lang attribute */
    document.documentElement.lang = lang;
  }

  window.SJ_toggleLang = function () {
    var next = getCurrentLang() === 'de' ? 'en' : 'de';
    localStorage.setItem(STORAGE_KEY, next);
    applyLang(next);
  };

  /* Apply on load */
  document.addEventListener('DOMContentLoaded', function () {
    applyLang(getCurrentLang());
  });
})();
