/* ============================================
   SHAYNA JUCKER – LANGUAGE SWITCHER
   DE (default) / EN
   ============================================ */

window.SJ_LANG = {
  de: {
    /* --- Index --- */
    'index.tagline':     'Event · Campaigns · Content · Projektmanagement',
    'index.bio':         'Ich bin Shayna – ich plane und inszeniere Brand Experiences, die Menschen bewegen. Nach 2+ Jahren bei Titbit mit Projekten für Migros suche ich eine strategischere Marketingrolle in Zürich, wo ich Kampagnen, Events und Markenauftritte von A bis Z verantworte.',
    'index.bio-p1':      'Brand- und Event-Managerin mit einer Leidenschaft dafür, Erlebnisse zu schaffen, die Menschen mit Marken verbinden. Mit Sitz in Zürich spezialisiere ich mich auf die Leitung grossangelegter Live-Aktivierungen und Markenkampagnen für bedeutende Schweizer Kunden – darunter der Auftritt von Migros an über 10 der ikonischsten Musikfestivals der Schweiz.',
    'index.bio-p2':      'Mit einem Hintergrund in Multimedia-Produktion, Design und strategischer Kommunikation bringe ich sowohl kreative Vision als auch operative Präzision in jedes Projekt – vom ersten Briefing bis zur finalen Umsetzung. Ich leite funktionsübergreifende Teams, betreue Kundenbeziehungen von A bis Z und übernehme die volle Verantwortung für die Ergebnisse.',
    'index.bio-p3':      'Getrieben von einer Leidenschaft für Marken, die inspirieren und Menschen bewegen.',
    'index.thesis':      'Meine Bachelorthesis: Brand Activism & Gen Z – wie Sportmarken Haltung zeigen →',
    'index.contact-cta': 'Du suchst jemanden für Brand Experience oder Marketing?',
    'index.btn-mail':    'Schreib mir',

    /* --- About --- */
    'about.role':            'Brand Experience &amp; Marketing',
    'about.desc':            'Brand- und Event-Managerin mit einer Leidenschaft dafür, Erlebnisse zu schaffen, die Menschen mit Marken verbinden. Mit Sitz in Zürich spezialisiere ich mich auf die Leitung grossangelegter Live-Aktivierungen und Markenkampagnen für bedeutende Schweizer Kunden – darunter der Auftritt von Migros an über 10 der ikonischsten Musikfestivals der Schweiz.',
    'about.desc2':           'Mit einem Hintergrund in Multimedia-Produktion, Design und strategischer Kommunikation bringe ich sowohl kreative Vision als auch operative Präzision in jedes Projekt – vom ersten Briefing bis zur finalen Umsetzung. Ich leite funktionsübergreifende Teams, betreue Kundenbeziehungen von A bis Z und übernehme die volle Verantwortung für die Ergebnisse.',
    'about.desc3':           'Getrieben von einer Leidenschaft für Marken, die inspirieren und Menschen bewegen.',
    'about.exp-heading':     'Erfahrung',
    'about.exp-sub':         'Berufliche Tätigkeiten',
    'about.edu-heading':     'Ausbildung',
    'about.edu-sub':         'Schulische Ausbildung',
    'about.int-heading':     'Interessen',
    'about.int-sub':         'Hobbys & Aktivitäten',
    'about.int-text':        'Eiskunstlauf | Surfen | Snowboard | Ski | Fussball | Sport allgemein | Reisen | Musik | Gitarre spielen | Fotografie | Bildbearbeitung | Grafik | Design | Genauigkeit | Zeit mit Familie & Freunden',

    /* --- Portfolio nav --- */
    'portfolio.design-group': 'Design & Studium',

    /* --- Marketing Cases --- */
    'mkt.tag1':           'Case Study 01',
    'mkt.title1':         'Migros – Schweizweite Festival-Experience 2023/24',
    'mkt.label.context':  'Ausgangslage',
    'mkt.label.role':     'Meine Rolle',
    'mkt.label.actions':  'Was ich gemacht habe',
    'mkt.label.result':   'Ergebnis',
    'mkt.label.learning': 'Was ich gelernt habe',
    'mkt.context1':       'Migros wollte an Schweizer Festivals präsent sein und junge Zielgruppen ansprechen. Titbit wurde beauftragt, Brand Activations zu entwickeln und umzusetzen – von der Konzeption bis zur Durchführung vor Ort.',
    'mkt.role1':          'Ich war verantwortlich für Projektplanung, Kundenabstimmungen mit Migros, Offertenerstellung, Koordination der Lieferanten und operative Durchführung vor Ort.',
    'mkt.action1.1':      'Konzept und Offerte für mehrere Festivaleinsätze erstellt',
    'mkt.action1.2':      'Wöchentliche Abstimmungsmeetings mit Migros-Ansprechperson geleitet',
    'mkt.action1.3':      'Content- und Social-Media-Begleitung der Events koordiniert',
    'mkt.action1.4':      'Aufbau, Durchführung und Abbau vor Ort geleitet',
    'mkt.action1.5':      'Nachbericht mit KPIs für Migros erstellt',
    'mkt.result1':        'Alle Festivaleinsätze erfolgreich durchgeführt. Migros-Kundschaft verlängerte die Zusammenarbeit für das Folgejahr. Positives Feedback auf den begleitenden Social-Media-Content.',
    'mkt.learning1':      'Wie wichtig klare Briefings und frühzeitige Kundenabstimmung sind – besonders wenn kurzfristige Änderungen vor Ort unvermeidlich sind.',
    'mkt.tag2':           'Case Study 02',
    'mkt.title2':         'Multimedia Award 2023 – Tonight Show Live Event',
    'mkt.context2':       'Für den Schweizer Multimedia Award sollte eine Live-Event-Show im Plaza Klub Zürich produziert werden – von der Konzeption bis zur Durchführung.',
    'mkt.role2':          'Ich habe das Showkonzept entwickelt, die Moderation übernommen, Regie geführt, die Kommunikation koordiniert und die technische Produktion geleitet.',
    'mkt.action2.1':      'Showkonzept und Ablaufplan entwickelt',
    'mkt.action2.2':      'Technische Anforderungen mit der Venue koordiniert',
    'mkt.action2.3':      'Moderation und Regie während der Live-Show übernommen',
    'mkt.action2.4':      'Kommunikation und Social Media rund um den Event betreut',
    'mkt.result2':        'Erfolgreiche Durchführung der Live-Show mit Publikum. Mediale Berichterstattung auf multimedia-award.ch.',
    'mkt.cta':            'Interesse an meiner Arbeit?',
    'mkt.btn-mail':       'Schreib mir',

    /* --- ON --- */
    'on.heading':      'Motivationsschreiben',
    'on.salutation':   'Liebes ON-Team',
    'on.p1':           'ON ignites the human spirit through movement. Meine Arbeit beginnt dort, wo eine Marke aufh&ouml;rt zu reden und anf&auml;ngt zu wirken.',
    'on.p2':           'Ich bringe nicht nur Erfahrung mit, sondern auch eine fundierte Perspektive auf ON als Brand. In meiner Bachelorarbeit habe ich die Brand-Activism-Kommunikationsstrategien von ON, Nike und Adidas wissenschaftlich analysiert und dabei verstanden, was ON von anderen unterscheidet: Authentizit&auml;t, die in der DNA sitzt, nicht auf der Kampagnenfl&auml;che klebt.',
    'on.p3':           'Was mich an ON reizt, ist genau dieser Anspruch. <em>Ignite the human spirit through movement</em> ersch&ouml;pft sich nicht in einem Messezelt. Er braucht Formate, die etwas ausl&ouml;sen, Experiences, die &uuml;ber den Moment hinausreichen und Menschen wirklich bewegen. Genau das ist der Massstab, an dem ich meine Arbeit messe.',
    'on.p4':           'Bei Tit-Pit habe ich schweizweit Brand Experiences f&uuml;r Marken wie Migros an &uuml;ber 10 Musikfestivals verantwortet &ndash; von der strategischen Konzeption und Offertenerstellung &uuml;ber Kundenabstimmungen bis zur operativen Umsetzung vor Ort. Parallel habe ich Content Marketing und Social-Media-Kommunikation rund um diese Formate geleitet, weil ein Event f&uuml;r mich erst dann wirklich funktioniert, wenn er ausserhalb des Moments weiterlebt und die Marke st&auml;rkt.',
    'on.p5':           'Diese Verbindung aus Campaign Management, Stakeholder-Verantwortung und operativer Pr&auml;zision ist mein Sweet Spot und passt genau auf das, was ON im Brand Experience-Umfeld bewegt.',
    'on.p6':           'Ich bringe Eigenverantwortung, Tempo und eine l&ouml;sungsorientierte Denkweise mit und bin &uuml;berzeugt, dass die st&auml;rksten Erlebnisse entstehen, wenn echte Begeisterung auf strategisches Denken trifft.',
    'on.closing':      'Keep moving,<br>Shayna Jucker',
    'on.lang-german':    'Deutsch',
    'on.lang-english':   'Englisch',
    'on.skills-heading': 'skills',
    'on.skills-sub':     'Sprachen | F&auml;higkeiten | Programme | Architektur',
    'on.cat-languages':  'Sprachen',
    'on.cat-abilities':  'F&auml;higkeiten',
    'on.cat-programs':   'Programme',
    'on.cat-architecture': 'Architektur',
    'on.cert-heading': 'Zertifikate',
    'on.cert-sub':     'ZERTIFIKATE &amp; NOTEN',
    'on.cert-btn':     'Arbeitszeugnisse &amp; Notenausweise',

    /* --- Bachelor --- */
    'bach.thesis-heading': 'Thesis',
    'bach.thesis-sub':     'All about Bachelorthesis',
    'bach.thesis-intro':   'Introduction',
    'bach.thesis-abs':     'Abstract',
    'bach.thesis-text':    'Brand Activism hat sich als Marketingstrategie etabliert, bei der Unternehmen zu gesellschaftlichen Themen Stellung beziehen. In der Sportbranche gewinnt dieses Konzept zunehmend an Bedeutung, insbesondere im Hinblick auf die Generation Z.',
    'bach.proj-heading':   'Projekt',
    'bach.proj-sub':       'All about Bachelorproject',
    'bach.proj-text':      'Im Rahmen des Bachelorprojekts wurde eine umfassende Corporate Identity und ein Corporate Design (CICD) für ein Bauberatungsunternehmen entwickelt.',
    /* --- Tiny Miracles --- */
    'tm.role':         'Promotion Coordinator 100% &middot; Z&uuml;rich Oerlikon',
    'tm.heading':      'Letter of motivation',
    'tm.salutation':   'Liebes Tiny Miracles-Team',
    'tm.p1':           'Wenn 40&rsquo;000 Menschen auf einem Feld stehen und der Abend l&auml;uft, hat Wochen vorher jemand eine Liste gef&uuml;hrt. Diese Rolle kenne ich &ndash; ich hatte sie in den letzten anderthalb Jahren an &uuml;ber zehn Schweizer Musikfestivals.',
    'tm.p2':           'Bei TIT-PIT verantworte ich die Brand Experiences von Migros an Festivals wie <strong>Frauenfeld</strong>, <strong>Pal&eacute;o</strong>, <strong>Gampel</strong>, <strong>Heitere</strong>, <strong>Moon &amp; Stars</strong> und <strong>Summerdays</strong> &ndash; vom Erstbriefing &uuml;ber Offerte und Konzept bis zur Umsetzung vor Ort. Ich koordiniere Teams, halte Timings, betreue Kunden und stehe am Aufbautag um sechs Uhr auf dem Gel&auml;nde. Was in eurem Inserat unter Koordination, Volunteers und Pr&auml;senz an Shows steht, ist f&uuml;r mich Alltag.',
    'tm.p3':           'Der zweite Teil dieser Rolle ist Sprache. Deutsch und Englisch sind bei mir beide Muttersprache &ndash; meine Mutter ist Amerikanerin. Bei TIT-PIT verantworte ich Social-Media-Content und Kundenkommunikation. Medienmitteilungen, Newsletter, Show-Announcements und Presale-Landingpages in beiden Sprachen zu schreiben und sauber zu redigieren, ist f&uuml;r mich kein Zusatz, sondern der Teil der Arbeit, den ich besonders gern mache.',
    'tm.p4':           'Warum Tiny Miracles? Weil hinter TAKK ab Entertainment die Shows stehen, f&uuml;r die sich Leute ein Jahr im Voraus einen Abend freihalten. Ich komme aus der Musik, ich spiele Gitarre, ich stehe seit Jahren an Festivals &ndash; und ich weiss, wie viel unsichtbare Koordination zwischen einem Ank&uuml;ndigungspost und dem Moment liegt, in dem das Licht ausgeht. In diesem Umfeld zu arbeiten ist f&uuml;r mich kein Stellenwechsel, sondern der logische n&auml;chste Schritt.',
    'tm.p5':           'Die Funktion als zentrale Koordinationsstelle zwischen CEO, Promotion Manager und Team liegt mir. Ich arbeite strukturiert, &uuml;bernehme Verantwortung ohne R&uuml;ckfrage-Schleife und bleibe ruhig, wenn zwei Stunden vor T&uuml;r&ouml;ffnung etwas kippt. Feedback nehme ich gerne entgegen &ndash; und gebe es genauso.',
    'tm.p6':           'Ehrlich sein will ich bei einem Punkt: Franz&ouml;sisch bringe ich nicht mit. Alles &Uuml;brige aus eurem Anforderungsprofil bringe ich mit &ndash; und Franz&ouml;sisch w&uuml;rde ich anpacken, wenn die Rolle es verlangt.',
    'tm.closing':      'Ich freue mich darauf, euch kennenzulernen.<br>Shayna Jucker',
    'tm.match-heading':'match',
    'tm.match-sub':    'Euer Inserat, Punkt f&uuml;r Punkt',
    'tm.m1-label':     'Promotion-Kampagnen unterst&uuml;tzen',
    'tm.m1-text':      '10+ Festival-Aktivierungen pro Jahr &ndash; Briefing, Timeline, Follow-up und Koordination externer Partner und Lieferanten.',
    'tm.m2-label':     'Kommunikationsmaterial verfassen',
    'tm.m2-text':      'Social-Media- und Kundenkommunikation bei TIT-PIT. Deutsch und Englisch Muttersprache, beide schriftlich auf Publikationsniveau.',
    'tm.m3-label':     'Volunteers &amp; Activation-Teams',
    'tm.m3-text':      'Einsatzplanung und F&uuml;hrung der Aktivierungs-Crews an Festivals: Schichten, Briefings, Nachschub und Qualit&auml;t vor Ort.',
    'tm.m4-label':     'Pr&auml;senz an Shows',
    'tm.m4-text':      'Jeden Sommer on-site: Aufbau, Betrieb, Abbau bei &uuml;ber zehn Festivals.',
    'tm.m5-label':     'Akkreditierungen &amp; Fotografen',
    'tm.m5-text':      'Erfahrung mit Medienpartnern, Fotografinnen und Fotografen sowie G&auml;stemanagement auf Festivalgel&auml;nden.',
    'tm.m6-label':     'Online-Werbekampagnen',
    'tm.m6-text':      'Content Marketing und Social Ads rund um Festivalauftritte. Adobe Creative Suite, Figma und Canva im t&auml;glichen Einsatz.',
    'tm.m7-label':     'Pr&auml;sentationen &amp; Reports',
    'tm.m7-text':      'Offerten, Konzepte und Post-Event-Reports mit KPIs f&uuml;r Kunden wie Migros. MS Office t&auml;glich im Einsatz.',
    'tm.m8-label':     'Koordinationsstelle im Team',
    'tm.m8-text':      'Bei TIT-PIT Schnittstelle zwischen Kunde, Kreation, Produktion und Crew &ndash; die Rolle, in der Informationen zusammenlaufen.',
    'tm.facts-label':  'Eckdaten',
    'tm.fact1':        'Verf&uuml;gbar per November 2026',
    'tm.fact2':        '100 % &ndash; Wohnort Pf&auml;ffikon ZH, rund 25 Minuten nach Z&uuml;rich Oerlikon',
    'tm.fact3':        'Deutsch und Englisch Muttersprache, Franz&ouml;sisch nicht vorhanden',
    'tm.fact4':        'BSc Multimedia Production FHGR, Vertiefung Live Communication',
    'tm.fact5':        'Bachelorarbeit: Brand Activism bei ON, Nike und Adidas',
    'tm.skills-heading':'skills',
    'tm.skills-sub':   'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'tm.cert-heading': 'documents',
    'tm.cert-sub':     'LEBENSLAUF, ARBEITSZEUGNISSE &amp; NOTENAUSWEISE',
    'tm.cv-btn':       'Lebenslauf',
    'tm.cert-btn':     'Arbeitszeugnisse &amp; Notenausweise',
    'tm.contact-cta':  'Fragen? Ich bin direkt erreichbar.',
    'tm.btn-mail':     'Schreib mir',

    /* --- Hallo (allgemeine Bewerbung) --- */
    'app.heading':     'Hallo.',
    'app.lead':        'Ich baue Markenerlebnisse, die nicht nur am Eventtag funktionieren.',
    'app.p1':          'Ich bin Shayna Jucker, 28, aus Pf&auml;ffikon ZH. Bei TIT-PIT verantworte ich die Brand Experiences von Migros an &uuml;ber zehn Schweizer Musikfestivals &ndash; vom ersten Briefing bis zum letzten Lastwagen, der das Gel&auml;nde verl&auml;sst.',
    'app.p2':          'Angefangen habe ich woanders: f&uuml;nf Jahre Zeichnerin Architektur, danach das Studium Multimedia Production mit Vertiefung Live Communication. Diese Kombination erkl&auml;rt, wie ich arbeite. Ich lese einen Standplan wie eine Zeichnerin, denke die Marke wie eine Strategin und stehe am Aufbautag um sechs Uhr auf dem Platz.',
    'app.p3':          'Diese Seite ist keine Bewerbung auf eine bestimmte Stelle. Sie zeigt, wof&uuml;r man mich holt &ndash; und wie ich arbeite, wenn es eng wird.',
    'app.roles-heading':'roles',
    'app.roles-sub':   'Wof&uuml;r man mich holt',
    'app.label-proof': 'Beleg',
    'app.label-role':  'Meine Rolle',
    'app.label-actions':'Konkret',
    'app.r1-title':    'Brand Experience &amp; Live-Events',
    'app.r1-sub':      'Markenauftritte, die vor Ort funktionieren und danach weiterleben',
    'app.r1-proof':    '10+ Schweizer Grossfestivals pro Jahr f&uuml;r Migros: Frauenfeld, Pal&eacute;o, Gampel, Heitere, Moon &amp; Stars, Stars in Town, Lumnezia, Luzern Live, Seaside, Summerdays und Summerstage.',
    'app.r1-role':     'Project Manager | Marketing, Events &amp; Brand Experience, TIT-PIT GmbH &ndash; mit voller Kundenverantwortung.',
    'app.r1-a1':       'Konzept und Offerte f&uuml;r Aktivierungen, Abstimmung direkt mit dem Kunden',
    'app.r1-a2':       'Lieferanten, Aufbauteams und Crews koordinieren',
    'app.r1-a3':       'Merci Bus Tour zum 100-Jahr-Jubil&auml;um von Migros (2025)',
    'app.r1-a4':       'Leitung der Mocktail Bar Tour 2026',
    'app.r1-a5':       'On-site Projektleitung: Aufbau, Betrieb, Abbau, Qualit&auml;tssicherung',
    'app.r2-title':    'Kampagnen, Content &amp; Kommunikation',
    'app.r2-sub':      'Text, Bild und Kanal so, dass die Marke danach st&auml;rker ist als vorher',
    'app.r2-proof':    'Deutsch und Englisch Muttersprache. Radioreporterin bei Radio S&uuml;dostschweiz, Social Media und Grafik bei TIT-PIT, Multimedia Design bei fliggs mobile.',
    'app.r2-role':     'Verantwortlich f&uuml;r Content, Grafik und Kundenkommunikation &ndash; von der Idee bis zum ver&ouml;ffentlichten Beitrag.',
    'app.r2-a1':       'Social-Media-Content und Redaktionsplanung rund um Live-Formate',
    'app.r2-a2':       'Grafik und Layout mit Adobe Creative Suite, Figma und Canva',
    'app.r2-a3':       'Kundenkommunikation und konsistente Markensprache &uuml;ber alle Touchpoints',
    'app.r2-a4':       'Recherche, Produktion und Moderation im Radio',
    'app.r2-a5':       'Bachelorarbeit &uuml;ber Brand Activism bei ON, Nike und Adidas',
    'app.r3-title':    'Projektleitung &amp; Koordination',
    'app.r3-sub':      'Die Stelle im Team, an der Informationen zusammenlaufen',
    'app.r3-proof':    'Seit 2020 durchgehend in projektverantwortlichen Rollen &ndash; erst in der Architektur, heute im Live-Marketing.',
    'app.r3-role':     'Schnittstelle zwischen Kunde, Kreation, Produktion und Crew. Entscheiden, priorisieren, nachfassen.',
    'app.r3-a1':       'Full Client Ownership vom Briefing bis zum Schlussrapport',
    'app.r3-a2':       'Budgetverantwortung und Offertwesen',
    'app.r3-a3':       'F&uuml;hrung interdisziplin&auml;rer Teams, auch ohne Weisungsbefugnis',
    'app.r3-a4':       'Termin- und Ablaufplanung &uuml;ber mehrere parallele Projekte',
    'app.r3-a5':       'Eigenst&auml;ndige Projektleitung nach 1.5 Jahren &uuml;bertragen bekommen',
    'app.how-heading': 'principles',
    'app.how-sub':     'Wie ich arbeite',
    'app.h1-label':    'Erst verstehen, dann versprechen',
    'app.h1-text':     'Ich sage einem Kunden lieber im Briefing, dass etwas nicht geht, als am Aufbautag. Das kostet einmal Mut und spart dreimal Geld.',
    'app.h2-label':    'Der Event ist nicht das Ziel',
    'app.h2-text':     'Ein Auftritt funktioniert f&uuml;r mich erst, wenn er ausserhalb des Moments weiterlebt. Deshalb denke ich Content von Anfang an mit, nicht als Nachtrag.',
    'app.h3-label':    'Ruhig bleiben ist eine F&auml;higkeit',
    'app.h3-text':     'Zwei Stunden vor T&uuml;r&ouml;ffnung kippt regelm&auml;ssig etwas. Wer dann Priorit&auml;ten setzt statt zu diskutieren, rettet den Abend.',
    'app.h4-label':    'Pl&auml;ne lesen k&ouml;nnen hilft',
    'app.h4-text':     'F&uuml;nf Jahre Architektur bedeuten: Ich sehe an einem Standplan, ob eine Idee gebaut werden kann, bevor sie jemand offeriert.',
    'app.facts-label': 'In Zahlen',
    'app.fact1':       '10+ Schweizer Grossfestivals pro Jahr in eigener Verantwortung',
    'app.fact2':       '2 Muttersprachen: Deutsch und Englisch',
    'app.fact3':       '5 Jahre Architektur: ArchiCAD, Vectorworks, 3D-Visualisierung',
    'app.fact4':       '1 Auslandsemester Transmedia Design in Tilburg, Niederlande',
    'app.fact5':       '100 Jahre Migros: Merci Bus Tour 2025',
    'app.skills-heading':'skills',
    'app.skills-sub':  'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'app.cert-heading':'documents',
    'app.cert-sub':    'LEBENSLAUF, ARBEITSZEUGNISSE &amp; NOTENAUSWEISE',
    'app.cv-btn':      'Lebenslauf',
    'app.cert-btn':    'Arbeitszeugnisse &amp; Notenausweise',
    'app.cases-btn':   'Cases ansehen',
    'app.contact-cta': 'Passt das zu einer Rolle bei euch?',
    'app.btn-mail':    'Schreib mir',
    'app.btn-linkedin':'LinkedIn',

    /* --- Bewerbung (allgemein) --- */
    'bw.role':         'Marketing &middot; Events &middot; Brand Experience',
    'bw.heading':      'Letter of motivation',
    'bw.salutation':   'Liebes Team',
    'bw.p1':           'Wenn 40&rsquo;000 Menschen auf einem Feld stehen und der Abend l&auml;uft, hat Wochen vorher jemand eine Liste gef&uuml;hrt. Diese Rolle kenne ich &ndash; ich hatte sie in den letzten anderthalb Jahren an &uuml;ber zehn Schweizer Musikfestivals. Meine Arbeit beginnt dort, wo eine Marke aufh&ouml;rt zu reden und anf&auml;ngt zu wirken.',
    'bw.p2':           'Bei TIT-PIT verantworte ich die Brand Experiences von Migros an Festivals wie <strong>Frauenfeld</strong>, <strong>Pal&eacute;o</strong>, <strong>Gampel</strong>, <strong>Heitere</strong>, <strong>Moon &amp; Stars</strong> und <strong>Summerdays</strong>. Vom Erstbriefing &uuml;ber Konzept und Budget bis zur Umsetzung vor Ort. Ich entwickle, wie sich die Marke auf dem Platz zeigt und was sie dort erz&auml;hlt, koordiniere Teams und Lieferanten und halte Timings und Budgets. Und ich stehe am Aufbautag um sechs Uhr auf dem Gel&auml;nde, weil ich sehen will, ob die Idee auch wirklich tr&auml;gt.',
    'bw.p2b':          'Gemacht habe ich das bisher aus der Agentur heraus, im Auftrag. Jetzt m&ouml;chte ich auf die andere Seite: eine Marke von innen mitgestalten, statt sie f&uuml;r andere zu bespielen. Was ich dorthin mitbringe, ist die Erfahrung von beiden Enden des Briefings. Ich weiss, wie eine Agentur denkt und rechnet, und was sie braucht, damit am Ende gute Arbeit zur&uuml;ckkommt.',
    'bw.p3':           'Deutsch und Englisch sind bei mir beide Muttersprache. Meine Mutter ist Amerikanerin. Bei TIT-PIT verantworte ich Social-Media-Content und Kundenkommunikation rund um diese Formate, weil ein Event f&uuml;r mich erst dann wirklich funktioniert, wenn er ausserhalb des Moments weiterlebt und die Marke st&auml;rkt. Konzepte und Texte in beiden Sprachen zu schreiben und sauber zu redigieren, ist f&uuml;r mich kein Zusatz, sondern der Teil der Arbeit, den ich besonders gern mache.',
    'bw.p4':           'Angefangen habe ich woanders. F&uuml;nf Jahre Zeichnerin EFZ Fachrichtung Architektur, dann Projektleitung, danach das Studium Multimedia Production mit Vertiefung Live Communication und ein Austauschsemester in den Niederlanden. In meiner Bachelorarbeit habe ich die Brand-Activism-Kommunikationsstrategien von ON, Nike und Adidas wissenschaftlich analysiert. Authentizit&auml;t sitzt in der DNA einer Marke, sie klebt nicht auf der Kampagnenfl&auml;che. Diese Kombination erkl&auml;rt, wie ich arbeite. Ich lese einen Standplan wie eine Zeichnerin, denke die Marke wie eine Strategin und behalte beides im Blick, wenn es eng wird.',
    'bw.p5':           'Diese Verbindung aus Campaign Management, Stakeholder-Verantwortung und operativer Pr&auml;zision ist mein Sweet Spot. Ich arbeite strukturiert, &uuml;bernehme Verantwortung ohne R&uuml;ckfrage-Schleife und bleibe ruhig, wenn zwei Stunden vor T&uuml;r&ouml;ffnung etwas kippt. Ich bringe Tempo und eine l&ouml;sungsorientierte Denkweise mit und sch&auml;tze den direkten Draht ins Team und zu den Menschen, mit denen ich arbeite.',
    'bw.p6':           'Was ich suche, ist eine Rolle im Marketing- oder Brand-Team einer Firma, die ihre eigene Marke f&uuml;hrt. Events, Kampagne, Markenauftritt und Content geh&ouml;ren f&uuml;r mich zusammen. Mich reizt, eine Marke &uuml;ber die Saison hinweg zu denken, statt sie f&uuml;r ein Wochenende aufzubauen und wieder abzubauen. Denn ein Markenversprechen ersch&ouml;pft sich nicht in einem Messezelt. Es braucht Formate, die etwas ausl&ouml;sen und Menschen wirklich bewegen.',
    'bw.closing':      'Ich bin &uuml;berzeugt, dass die st&auml;rksten Erlebnisse entstehen, wenn echte Begeisterung auf strategisches Denken trifft. Alles Weitere gerne im Gespr&auml;ch. Ich freue mich darauf, euch kennenzulernen.<br>Shayna Jucker',
    'bw.skills-heading':'skills',
    'bw.skills-sub':   'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'bw.cert-heading': 'documents',
    'bw.cert-sub':     'LEBENSLAUF, ARBEITSZEUGNISSE &amp; NOTENAUSWEISE',
    'bw.cv-btn':       'Lebenslauf',
    'bw.cert-btn':     'Arbeitszeugnisse &amp; Notenausweise',
    'bw.contact-cta':  'Fragen? Ich bin direkt erreichbar.',
    'bw.btn-mail':     'Schreib mir',

    /* --- Arbeitsprobe Presale --- */
    'ps.eyebrow':      'Arbeitsprobe f&uuml;r Tiny Miracles Communication AG',
    'ps.heading':      'Presale-Landingpage',
    'ps.lead':         'Im Inserat steht &laquo;presale landing pages&raquo;. Statt zu schreiben, dass ich das kann, habe ich eine gebaut.',
    'ps.p1':           'Eine Presale-Seite hat genau eine Aufgabe: Zwischen Ank&uuml;ndigung und Verkaufsstart darf keine Frage offen bleiben, die sonst im Info-Postfach landet. Jede Frage, die die Seite beantwortet, ist eine Mail, die niemand beantworten muss.',
    'ps.p2':           'Deshalb ist sie nicht nach Sch&ouml;nheit sortiert, sondern nach der Reihenfolge, in der Leute denken: Wann? Wie komme ich an den Code? Was kostet es? Darf ich rein? Und als Medium: wer ist meine Ansprechperson?',
    'ps.p3':           'Der Countdown kennt vier Zust&auml;nde &ndash; vor dem Presale, w&auml;hrend des Presales, zwischen Presale und freiem Verkauf, danach. Eine Seite, die am Verkaufstag noch &laquo;startet in 0 Tagen&raquo; anzeigt, kostet Vertrauen. Genau solche Details entscheiden, ob eine Ank&uuml;ndigung sauber l&auml;uft oder Support ausl&ouml;st.',
    'ps.p4':           'Technisch ist es eine einzige HTML-Datei: kein Framework, keine Build-Tools, keine externen Requests. F&uuml;r die n&auml;chste Show werden acht Werte getauscht &ndash; Act, Tour, Datum, Venue, drei Verkaufszeitpunkte, Preise. Deutsch und Englisch sind eingebaut.',
    'ps.btn-demo':     'Landingpage &ouml;ffnen',
    'ps.btn-pr':       'Medienmitteilung DE / EN',
    'ps.does-heading': 'details',
    'ps.does-sub':     'Was die Seite leistet',
    'ps.d1-label':     'Alle Termine an einem Ort',
    'ps.d1-text':      'Code-Versand, Presale-Fenster und freier Verkauf stehen mit Datum und Uhrzeit auf der Seite. Das sind die drei Fragen, die sonst einzeln per Mail kommen.',
    'ps.d2-label':     'Vier Countdown-Zust&auml;nde',
    'ps.d2-text':      'Die Seite bleibt korrekt, auch wenn sie am Verkaufstag niemand anfasst. Nach dem Verkaufsstart verschwindet der Z&auml;hler von selbst.',
    'ps.d3-label':     'Zweisprachig ab Werk',
    'ps.d3-text':      'Deutsch und Englisch liegen in derselben Datei, umschaltbar per Klick. Kein zweites Template, keine zweite Pflegestelle.',
    'ps.d4-label':     'Akkreditierung vorweg gekl&auml;rt',
    'ps.d4-text':      'Frist, Regeln im Graben und Ansprechperson stehen direkt auf der Seite. Das nimmt vor jeder Show einen Stapel Einzelanfragen weg.',
    'ps.d5-label':     'Barrierefreiheit und Resale beantwortet',
    'ps.d5-text':      'Rollstuhlpl&auml;tze, Begleitticket und Zweitmarkt sind die zwei Themen, die sonst zuverl&auml;ssig im Postfach landen. Beide sind in der FAQ abgeholt.',
    'ps.d6-label':     'Eine Datei, keine Abh&auml;ngigkeiten',
    'ps.d6-text':      'L&auml;uft auf jedem Hosting, l&auml;dt nichts von aussen nach und ist in etwa zehn Minuten auf die n&auml;chste Show angepasst.',
    'ps.honest-label': 'Ehrlichkeitshalber',
    'ps.honest1':      'Luma Rivers, Nils Bregenz, Datum und Preise sind frei erfunden',
    'ps.honest2':      'Kein offizielles Material eines Veranstalters, kein Bezug zu einer real geplanten Show',
    'ps.honest3':      'Als Pressekontakt steht bewusst meine eigene Adresse',
    'ps.honest4':      'Das Newsletter-Feld ist absichtlich deaktiviert &ndash; eine Arbeitsprobe sammelt keine Adressen',
    'ps.honest5':      'Gebaut am Wochenende, in unter einem Tag',
    'ps.pr-heading':   'press release',
    'ps.pr-sub':       'Show-Announcement zur gleichen Show',
    'ps.pr-text':      'Zur Landingpage geh&ouml;rt die Medienmitteilung, weil in der Praxis beides am selben Morgen rausgeht. Deutsch und Englisch, im &uuml;blichen Aufbau: Sperrfrist, Ort und Datum, Lead mit den W-Fragen, Zitat, Ticketing-Block, Kurzportr&auml;t und Medienkontakt. Das ist gleichzeitig meine Schreibprobe in beiden Sprachen.',
    'ps.btn-pr2':      'Medienmitteilung DE / EN',
    'ps.btn-back':     'Zur Bewerbung',
    'ps.contact-cta':  'Fragen zur Arbeitsprobe? Gerne direkt.',
    'ps.btn-mail':     'Schreib mir',
    'tm.sample-heading':'work sample',
    'tm.sample-sub':   'Statt Behauptung: die Arbeit selbst',
    'tm.sample-text':  'Euer Inserat nennt &laquo;presale landing pages&raquo; als Aufgabe. Ich habe eine gebaut &ndash; mit Countdown &uuml;ber vier Verkaufszust&auml;nde, FAQ, Akkreditierungsregeln, Deutsch und Englisch, als eine einzige Datei ohne Abh&auml;ngigkeiten. Dazu die passende Medienmitteilung in beiden Sprachen. Die Show darin ist frei erfunden, die Mechanik ist echt.',
    'tm.sample-btn':   'Arbeitsprobe ansehen',

    /* --- Bewerbung Zweifel Weine & Getränke --- */
    'zw.role':          'Marketing &amp; Design &middot; Zweifel Weine &amp; Getr&auml;nke Gruppe',
    'zw.heading':       'Letter of motivation',
    'zw.salutation':    'Guten Tag Herr Frischknecht',
    'zw.p1':            'Ein neuer Wein kommt ins Sortiment. Er braucht einen Regal-Talker, eine Degustationskarte, ein Verkaufsblatt f&uuml;r die Gastronomie und einen Post. Vier Materialien, vier Mal dieselben Angaben, vier Gelegenheiten, dass Jahrgang oder Preis auseinanderlaufen. Statt Ihnen zu schreiben, dass ich so etwas kann, habe ich es gebaut: einen Baukasten, der aus einer einzigen Dateneingabe alle vier Materialien druckfertig erzeugt. Er steht weiter unten auf dieser Seite.',
    'zw.p2':            'Bei TIT-PIT verantworte ich die Brand Experiences von Migros an &uuml;ber zehn Schweizer Musikfestivals &ndash; <strong>Frauenfeld</strong>, <strong>Pal&eacute;o</strong>, <strong>Gampel</strong>, <strong>Heitere</strong>, <strong>Moon &amp; Stars</strong>, <strong>Summerdays</strong>. Vom Erstbriefing &uuml;ber Konzept, Offerte und Budget bis zur Umsetzung vor Ort. Dazu kommt alles, was daran h&auml;ngt: Gestaltung der Materialien, Social-Media-Content, Kundenkommunikation, Koordination von Lieferanten und Produktionen. Ich bin die Stelle, an der Marke, Produktion und Budget zusammenlaufen &ndash; und ich stehe am Aufbautag um sechs auf dem Gel&auml;nde, weil ich sehen will, ob die Idee auch wirklich tr&auml;gt.',
    'zw.p3':            'Der Bezug zu Getr&auml;nken ist bei mir nicht theoretisch: 2026 leite ich die <strong>Mocktail Bar Tour</strong> f&uuml;r Migros &ndash; Getr&auml;nke, Ausschank und Markenauftritt an wechselnden Standorten, mit allem, was dazugeh&ouml;rt: Produkt erkl&auml;ren, Personal briefen, Nachschub sichern, Bildmaterial produzieren.',
    'zw.p5':            'Studiert habe ich Multimedia Production an der FHGR mit Vertiefung Live Communication. In meiner Bachelorarbeit habe ich die Brand-Activism-Strategien von ON, Nike und Adidas analysiert. Was ich daraus mitgenommen habe, benutze ich seither t&auml;glich: Eine Marke &uuml;berzeugt nicht dort, wo sie am lautesten ist, sondern dort, wo sie &uuml;ber Jahre dasselbe tut.',
    'zw.p6':            'Zu den KI-Tools, weil das in der Stellenanzeige ausdr&uuml;cklich steht: Damit arbeite ich t&auml;glich &ndash; f&uuml;r Rohentw&uuml;rfe und Textvarianten, f&uuml;r Konzeptideen und vor allem in der Bildbearbeitung, vom Freistellen und Retuschieren bis zum Anpassen von Bildformaten f&uuml;r die verschiedenen Kan&auml;le. Ich glaube an diese Werkzeuge. Sie nehmen einem nicht die Arbeit ab, aber den Leerlauf: Was fr&uuml;her ein halber Tag Handarbeit war, ist heute eine Viertelstunde &ndash; und die gewonnene Zeit fliesst dorthin, wo sie z&auml;hlt, in die Idee dahinter. Man soll damit arbeiten, statt Angst davor zu haben. Wer sie beherrscht, probiert mehr aus und kommt am Ende zu besseren Ergebnissen.',
    'zw.p7':            'Warum Zweifel? Ganz ehrlich: Den Namen kenne ich, seit ich denken kann &ndash; als Kind allerdings vom Chips-Sack, nicht von der Weinkarte. Dass die Chips einst aus der Mosterei in H&ouml;ngg kamen und damit aus demselben Haus, das 1898 mit Wein und Getr&auml;nken angefangen hat, habe ich erst sp&auml;ter gelernt. Und die Weine mag ich heute nat&uuml;rlich genauso. Genau diese lange Wurzel reizt mich: eine Marke, die nicht f&uuml;r ein Wochenende aufgebaut und wieder abgebaut wird, sondern seit &uuml;ber 125 Jahren w&auml;chst. Daran m&ouml;chte ich mitbauen.',
    'zw.closing':       'Alles Weitere gerne im Gespr&auml;ch.<br>Freundliche Gr&uuml;sse<br>Shayna Jucker',
    'zw.sample-heading':'work sample',
    'zw.sample-sub':    'Statt Behauptung: die Arbeit selbst',
    'zw.sample-p1':     '<strong>&laquo;Weinblatt&raquo; &ndash; ein Wein, vier Materialien, ein Layoutsystem.</strong> Weindaten einmal eintippen, und Regal-Talker, Degustationskarte, Gastro-Verkaufsblatt und Social-Kachel entstehen gleichzeitig. Jedes Material druckt im echten Endformat: 55&times;105 mm, A6 quer, A5. Die Social-Kachel l&auml;sst sich als SVG herunterladen und in Illustrator weiterbauen.',
    'zw.sample-p2':     'Drei Dinge daran sind mir wichtiger als die Optik. <strong>Erstens:</strong> Der Akzent wechselt mit der Weinkategorie, Raster und Typografie bleiben &ndash; so ist das Corporate Design im System verankert und nicht in der Disziplin der Person, die gerade Zeit hat. <strong>Zweitens:</strong> Derselbe Wein wird in drei Tonalit&auml;ten erz&auml;hlt &ndash; am Regal knapp, im Gastro-Termin fachlich, auf Social locker. Das ist Textarbeit, keine Formatfrage. <strong>Drittens:</strong> Das Verkaufsblatt rechnet aus Einkaufspreis und Faktor den empfohlenen Flaschen- und Offenausschankpreis. Das ist die Zahl, nach der in der Gastronomie als Erstes gefragt wird.',
    'zw.sample-p3':     'Alle Weine, Preise und Auszeichnungen darin sind frei erfunden, die Wortmarke ist ein Platzhalter, und es ist kein offizielles Material Ihres Hauses. Technisch ist es eine einzige HTML-Datei: kein Framework, keine externen Requests, keine Datenerfassung. Zweisprachig Deutsch und Englisch. Entstanden an einem Wochenende.',
    'zw.sample-btn':    'Baukasten &ouml;ffnen',
    'zw.cases-btn':     'Marketing-Cases ansehen',
    'zw.match-heading': 'match',
    'zw.match-sub':     'Ihre Stellenanzeige, Punkt f&uuml;r Punkt',
    'zw.m1-label':      'Markenauftritt weiterentwickeln',
    'zw.m1-text':       'Brand Management und Brand Experience seit anderthalb Jahren t&auml;glich &ndash; Markenauftritte konzipieren, gestalten und &uuml;ber eine ganze Saison konsistent halten.',
    'zw.m2-label':      'Corporate Identity &uuml;ber alle Kan&auml;le',
    'zw.m2-text':       'Bei TIT-PIT verantworte ich den eigenen Markenauftritt &uuml;ber alle Touchpoints. Meine Arbeitsprobe zeigt, wie ich CI systematisch verankere statt sie zu kontrollieren.',
    'zw.m3-label':      'Print, Digital und POS',
    'zw.m3-text':       'Von Standbau-Layout und Beschriftung &uuml;ber Flyer und Verkaufsunterlagen bis zu Social-Assets. Reinzeichnung und Druckdatenaufbereitung inklusive &ndash; das kommt aus f&uuml;nf Jahren Architekturzeichnen.',
    'zw.m4-label':      'Visuelle Konzepte f&uuml;r Kampagnen',
    'zw.m4-text':       'Konzepte f&uuml;r Migros-Aktivierungen an &uuml;ber zehn Festivals: Idee, Bildwelt, Mechanik und Umsetzung, jeweils vom Erstbriefing bis zum Abbau.',
    'zw.m5-label':      'Kampagnen planen und umsetzen',
    'zw.m5-text':       'Campaign Management mit Timeline, Budget, Lieferanten und Nachbericht. Post-Event-Reports mit KPIs f&uuml;r Kunden geh&ouml;ren zum Standard.',
    'zw.m6-label':      'Content f&uuml;r Social, Newsletter, Website',
    'zw.m6-text':       'Verantwortung f&uuml;r Social-Media-Content und Kundenkommunikation bei TIT-PIT. Deutsch und Englisch Muttersprache, beide schriftlich auf Publikationsniveau.',
    'zw.m7-label':      'Alle Unterlagen selbstst&auml;ndig',
    'zw.m7-text':       'Adobe Creative Cloud t&auml;glich: InDesign, Illustrator, Photoshop, Premiere Pro, After Effects, Lightroom. Dazu Figma, Canva und Webseiten. Ich brauche f&uuml;r ein Verkaufsblatt keine Agentur.',
    'zw.m8-label':      'KI-Tools im Content-Prozess',
    'zw.m8-text':       'T&auml;glich im Einsatz f&uuml;r Rohentw&uuml;rfe, Varianten und Bildaufbereitung &ndash; mit klarer Grenze: Der Entwurf darf aus dem Tool kommen, der Text, der rausgeht, ist redigiert.',
    'zw.m9-label':      'Verkaufsunterlagen &amp; Weinmarketing',
    'zw.m9-text':       'Offerten, Konzepte und Verkaufsunterlagen f&uuml;r Kunden wie Migros. Wie ich Gastro- und Handelsunterlagen aufbaue, zeigt der Baukasten inklusive Kalkulationshilfe.',
    'zw.m10-label':     'Lieferantenkampagnen',
    'zw.m10-text':      'Kampagnen mit externen Partnern und deren Vorgaben umzusetzen, ist Agenturalltag: fremde Guidelines respektieren und trotzdem den eigenen Auftritt halten.',
    'zw.m11-label':     'Degustationen, Messen, Kundenevents',
    'zw.m11-text':      'Live-Kommunikation ist meine Studienvertiefung und mein Beruf: &uuml;ber zehn Grossanl&auml;sse pro Jahr, plus Moderation und Regie beim Multimedia Award 2023 im Plaza Z&uuml;rich.',
    'zw.m12-label':     'Projekte, Agenturen, Budget',
    'zw.m12-text':      'Projektleitung seit 2020, zuerst in der Architektur, heute im Marketing. Budgetverantwortung, Produktionskoordination und Agentur- und Lieferantensteuerung von beiden Seiten des Briefings.',
    'zw.facts-label':   'Eckdaten &ndash; auch die unbequemen',
    'zw.fact1':         'Verf&uuml;gbar per November 2026',
    'zw.fact2':         'Wohnort Pf&auml;ffikon ZH &ndash; rund 15 Minuten nach Volketswil, rund 30 nach Z&uuml;rich-H&ouml;ngg',
    'zw.fact3':         'Deutsch und Englisch Muttersprache &ndash; Italienisch bringe ich nicht mit',
    'zw.fact4':         'Keine Berufserfahrung in der Wein- und Getr&auml;nkebranche, aber Erfahrung mit Getr&auml;nke-Aktivierungen und Ausschank an Publikumsanl&auml;ssen',
    'zw.fact5':         'Zeichnerin EFZ Fachrichtung Architektur &ndash; f&uuml;nf Jahre Reinzeichnung und Massgenauigkeit',
    'zw.fact6':         'BSc Multimedia Production FHGR, Vertiefung Live Communication, Austauschsemester in den Niederlanden',
    'zw.fact7':         'Bachelorarbeit: Brand Activism bei ON, Nike und Adidas',
    'zw.skills-heading':'skills',
    'zw.skills-sub':    'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'zw.cert-heading':  'documents',
    'zw.cert-sub':      'LEBENSLAUF, ARBEITSZEUGNISSE &amp; NOTENAUSWEISE',
    'zw.cv-btn':        'Lebenslauf',
    'zw.cert-btn':      'Arbeitszeugnisse &amp; Notenausweise',
    'zw.contact-cta':   'Fragen? Ich bin direkt erreichbar.',
    'zw.btn-mail':      'Schreib mir',

    /* --- ON Brand & Event Marketing Manager --- */
    'obe.role':          'Brand &amp; Event Marketing Manager &middot; ON',
    'obe.heading':       'Letter of motivation',
    'obe.salutation':    'Liebes ON-Team',
    'obe.p1':            'ON ignites the human spirit through movement. Meine Arbeit beginnt dort, wo eine Marke aufh&ouml;rt zu reden und anf&auml;ngt zu wirken.',
    'obe.p1b':           'Statt euch zu schreiben, dass ich Marke und Umsetzung zusammendenke, habe ich es gezeigt: <strong>&laquo;H&ouml;henmeter&raquo;</strong> &ndash; ein Kampagnenkonzept f&uuml;r ON in drei Key Visuals. Es steht weiter unten auf dieser Seite.',
    'obe.p2':            'Ich bringe nicht nur Erfahrung mit, sondern auch eine fundierte Perspektive auf ON als Brand. In meiner Bachelorarbeit habe ich die Brand-Activism-Kommunikationsstrategien von ON, Nike und Adidas wissenschaftlich analysiert und dabei verstanden, was ON von anderen unterscheidet: Authentizit&auml;t, die in der DNA sitzt, nicht auf der Kampagnenfl&auml;che klebt.',
    'obe.p3':            'Was mich an ON reizt, ist genau dieser Anspruch. <em>Ignite the human spirit through movement</em> ersch&ouml;pft sich nicht in einem Messezelt. Er braucht Formate, die etwas ausl&ouml;sen, Experiences, die &uuml;ber den Moment hinausreichen und Menschen wirklich bewegen. Genau das ist der Massstab, an dem ich meine Arbeit messe.',
    'obe.p4':            'Bei Tit-Pit habe ich schweizweit Brand Experiences f&uuml;r Marken wie Migros an &uuml;ber 10 Musikfestivals verantwortet &ndash; von der strategischen Konzeption und Offertenerstellung &uuml;ber Kundenabstimmungen bis zur operativen Umsetzung vor Ort. Parallel habe ich Content Marketing und Social-Media-Kommunikation rund um diese Formate geleitet, weil ein Event f&uuml;r mich erst dann wirklich funktioniert, wenn er ausserhalb des Moments weiterlebt und die Marke st&auml;rkt.',
    'obe.p5':            'Diese Verbindung aus Campaign Management, Stakeholder-Verantwortung und operativer Pr&auml;zision ist mein Sweet Spot und passt genau auf das, was ON im Brand Experience-Umfeld bewegt.',
    'obe.p6':            'Ich bringe Eigenverantwortung, Tempo und eine l&ouml;sungsorientierte Denkweise mit und bin &uuml;berzeugt, dass die st&auml;rksten Erlebnisse entstehen, wenn echte Begeisterung auf strategisches Denken trifft.',
    'obe.p7':            'Warum ON? Ganz ehrlich: Ich habe diese Marke schon einmal ein halbes Jahr lang auseinandergenommen &ndash; f&uuml;r meine Bachelorarbeit, von aussen, mit Quellenverzeichnis. Am Ende stand nicht nur eine Note, sondern eine Sympathie, die ich nicht geplant hatte: eine Schweizer Marke, die in einer Werkstatt angefangen hat und heute weltweit l&auml;uft, ohne dabei laut zu werden. Genau das reizt mich &ndash; nach anderthalb Jahren Agentur, in denen ich Marken f&uuml;r andere bespielt habe, m&ouml;chte ich eine von innen mitbauen. Und zwar diese.',
    'obe.closing':       'Alles Weitere gerne im Gespr&auml;ch.<br>Keep moving,<br>Shayna Jucker',
    'obe.cert-heading':  'documents',
    'obe.cert-sub':      'LEBENSLAUF, ARBEITSZEUGNISSE &amp; NOTENAUSWEISE',
    'obe.cv-btn':        'Lebenslauf',
    'obe.cert-btn':      'Arbeitszeugnisse &amp; Notenausweise',
    'obe.contact-cta':   'Fragen? Ich bin direkt erreichbar.',
    'obe.btn-mail':      'Schreib mir',
    'obe.sample-heading':'work sample',
    'obe.sample-sub':    'Statt Behauptung: die Arbeit selbst',
    'obe.sample-p1':     '<strong>&laquo;H&ouml;henmeter&raquo;</strong> &ndash; ein Kampagnenkonzept f&uuml;r ON in drei Key Visuals. Die H&ouml;henkurve der Landeskarte als Bildsprache: jedes Motiv eine Route, gezeichnet wie eine Karte, mit ihrem H&ouml;henprofil als Signatur. Idee, Claim, Headlines und Gestaltung von mir &ndash; fiktiv, aber als System gebaut, das auf jedes Gel&auml;nde und jedes Format &uuml;bersetzt.',
    'obe.sample-btn':    'Kampagne ansehen',
    'obe.match-heading': 'match',
    'obe.match-sub':     'Die Rolle, Punkt f&uuml;r Punkt',
    'obe.m1-label':      'Brand Experiences konzipieren',
    'obe.m1-text':       'Seit anderthalb Jahren t&auml;glich: Markenauftritte f&uuml;r Migros an &uuml;ber zehn Schweizer Festivals &ndash; Frauenfeld, Pal&eacute;o, Gampel, Heitere, Moon &amp; Stars, Summerdays. Idee, Bildwelt, Mechanik, Umsetzung.',
    'obe.m2-label':      'Events von A bis Z umsetzen',
    'obe.m2-text':       'Vom Erstbriefing &uuml;ber Offerte, Standplan und Lieferantenkoordination bis zum Abbau. Ich stehe am Aufbautag um sechs auf dem Gel&auml;nde, weil ich sehen will, ob die Idee auch wirklich tr&auml;gt.',
    'obe.m3-label':      'Formate skalierbar machen',
    'obe.m3-text':       'Ein System, viele Anwendungen: Meine Arbeitsprobe zeigt eine Bildsprache, die &uuml;ber Gel&auml;nde, Sprachen und Formate hinweg gleich bleibt &ndash; genau das braucht es, wenn dasselbe Bild in f&uuml;nfzehn M&auml;rkten funktionieren soll.',
    'obe.m4-label':      'Markenstandard halten',
    'obe.m4-text':       'Bei TIT-PIT verantworte ich den eigenen Markenauftritt &uuml;ber alle Touchpoints. Ich verankere CI im System statt sie zu kontrollieren &ndash; das ist der einzige Weg, der eine Saison &uuml;berlebt.',
    'obe.m5-label':      'Budget und Timeline',
    'obe.m5-text':       'Budgetverantwortung pro Projekt, Offerten, Nachkalkulation und Post-Event-Reports mit KPIs f&uuml;r den Kunden. Kosten pro Kontakt ist f&uuml;r mich keine Theoriegr&ouml;sse.',
    'obe.m6-label':      'Agenturen und Partner steuern',
    'obe.m6-text':       'Ich kenne beide Seiten des Briefings. Aus der Agentur weiss ich, was ein gutes Briefing ausl&ouml;st, wo Puffer versteckt sind und wie man Produktionen sauber durchbekommt.',
    'obe.m7-label':      'Content rund um Events',
    'obe.m7-text':       'Social-Media-Content und Kundenkommunikation rund um jedes Format &ndash; weil ein Event erst dann funktioniert, wenn er ausserhalb des Moments weiterlebt. Foto, Video, Schnitt und Text mache ich selbst.',
    'obe.m8-label':      'Deutsch und Englisch',
    'obe.m8-text':       'Beide Muttersprache, meine Mutter ist Amerikanerin. Konzepte, Briefings und Captions schreibe und redigiere ich in beiden Sprachen auf Publikationsniveau &ndash; diese Seite und die Arbeitsprobe sind der Beleg.',
    'obe.m9-label':      'Community und Retail',
    'obe.m9-text':       '2026 leite ich die Mocktail Bar Tour f&uuml;r Migros: Ausschank und Markenauftritt an wechselnden Standorten, mit Personalbriefing, Nachschub und Bildmaterial. Wiederkehr statt Reichweite ist dort die Kennzahl.',
    'obe.m10-label':     'Cross-funktional arbeiten',
    'obe.m10-text':      'Zwischen Kunde, Kreation, Produktion und Crew zu &uuml;bersetzen, ist mein Alltag. Projektleitung seit 2020 &ndash; zuerst in der Architektur, heute im Marketing.',
    'obe.m11-label':     'Selbst gestalten k&ouml;nnen',
    'obe.m11-text':      'Adobe Creative Cloud t&auml;glich: InDesign, Illustrator, Photoshop, Premiere Pro, After Effects, Lightroom. Dazu Figma, Canva und Webseiten. F&uuml;r einen Standplan oder ein Briefing brauche ich keine Agentur.',
    'obe.m12-label':     'KI-Tools im Prozess',
    'obe.m12-text':      'T&auml;glich im Einsatz f&uuml;r Rohentw&uuml;rfe, Varianten und Bildaufbereitung &ndash; mit klarer Grenze: Der Entwurf darf aus dem Tool kommen, der Text, der rausgeht, ist redigiert. Auch diese Kampagne ist so entstanden.',
    'obe.facts-label':   'Eckdaten &ndash; auch die unbequemen',
    'obe.fact1':         'Verf&uuml;gbar per November 2026',
    'obe.fact2':         'Wohnort Pf&auml;ffikon ZH &ndash; rund 30 Minuten nach Z&uuml;rich',
    'obe.fact3':         'Deutsch und Englisch Muttersprache',
    'obe.fact4':         'Keine Berufserfahrung in der Sportartikelbranche &ndash; daf&uuml;r &uuml;ber zehn Grossanl&auml;sse pro Jahr, vom Konzept bis zum Abbau',
    'obe.fact5':         'Zeichnerin EFZ Fachrichtung Architektur &ndash; f&uuml;nf Jahre Reinzeichnung und Massgenauigkeit',
    'obe.fact6':         'BSc Multimedia Production FHGR, Vertiefung Live Communication, Austauschsemester in den Niederlanden',
    'obe.fact7':         'Bachelorarbeit: Brand Activism bei ON, Nike und Adidas',
    'obe.skills-heading':'skills',
    'obe.skills-sub':    'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
  },

  en: {
    /* --- Index --- */
    'index.tagline':     'Events · Campaigns · Content · Project Management',
    'index.bio':         'I\'m Shayna – I plan and stage brand experiences that move people. After 2+ years at Titbit on projects for Migros, I\'m looking for a more strategic marketing role in Zurich, where I can own campaigns, events and brand activations from A to Z.',
    'index.bio-p1':      'Brand and Event Manager with a passion for creating experiences that connect people with brands. Based in Zurich, I specialise in managing large-scale live activations and brand campaigns for major Swiss clients – including Migros\' presence at 10+ of Switzerland\'s most iconic music festivals.',
    'index.bio-p2':      'With a background in multimedia production, design and strategic communication, I bring both creative vision and operational precision to every project – from first briefing to final execution. I lead cross-functional teams, manage client relationships end-to-end and take full ownership of results.',
    'index.bio-p3':      'Driven by a passion for brands that inspire and move people.',
    'index.thesis':      'My Bachelor Thesis: Brand Activism & Gen Z – how sports brands take a stand →',
    'index.contact-cta': 'Looking for someone in Brand Experience or Marketing?',
    'index.btn-mail':    'Write me',

    /* --- About --- */
    'about.role':            'Brand Experience &amp; Marketing',
    'about.desc':            'Brand and event professional with a passion for creating experiences that connect people with brands. Based in Zurich, I specialise in managing large-scale live activations and brand campaigns for major Swiss clients – including Migros\' presence at 10+ of Switzerland\'s most iconic music festivals.',
    'about.desc2':           'With a background in multimedia production, design and strategic communication, I bring both creative vision and operational precision to every project – from first briefing to final execution. I lead cross-functional teams, manage client relationships end-to-end and take full ownership of results.',
    'about.desc3':           'Driven by a passion for brands that inspire and move people.',
    'about.exp-heading':     'Experience',
    'about.exp-sub':         'Occupational activities',
    'about.edu-heading':     'Education',
    'about.edu-sub':         'School education',
    'about.int-heading':     'Interests',
    'about.int-sub':         'Hobbies & Activities',
    'about.int-text':        'Figure Skat | Surf | Snowboard | Ski | Soccer | Sports in General | Travel | Music | Playing Guitar | Photography | Image Editing | Graphics | Design | Attention to Detail | Keeping in touch with Family & Friends',

    /* --- Portfolio nav --- */
    'portfolio.design-group': 'Design & Studies',

    /* --- Marketing Cases --- */
    'mkt.tag1':           'Case Study 01',
    'mkt.title1':         'Migros – Nationwide Festival Experience 2023/24',
    'mkt.label.context':  'Background',
    'mkt.label.role':     'My Role',
    'mkt.label.actions':  'What I Did',
    'mkt.label.result':   'Results',
    'mkt.label.learning': 'What I Learned',
    'mkt.context1':       'Migros wanted to be present at Swiss festivals and reach younger audiences. Titbit was commissioned to develop and execute brand activations – from concept to on-site delivery.',
    'mkt.role1':          'I was responsible for project planning, client coordination with Migros, quote preparation, supplier coordination and operational on-site management.',
    'mkt.action1.1':      'Created concepts and quotes for multiple festival activations',
    'mkt.action1.2':      'Led weekly alignment meetings with the Migros contact',
    'mkt.action1.3':      'Coordinated content and social media coverage of the events',
    'mkt.action1.4':      'Managed on-site setup, execution and teardown',
    'mkt.action1.5':      'Created post-event report with KPIs for Migros',
    'mkt.result1':        'All festival activations successfully delivered. Migros extended the partnership for the following year. Positive feedback on the accompanying social media content.',
    'mkt.learning1':      'How important clear briefings and early client alignment are – especially when last-minute changes on site are unavoidable.',
    'mkt.tag2':           'Case Study 02',
    'mkt.title2':         'Multimedia Award 2023 – Tonight Show Live Event',
    'mkt.context2':       'A live event show at Plaza Klub Zurich was to be produced for the Swiss Multimedia Award – from concept to execution.',
    'mkt.role2':          'I developed the show concept, hosted the event, directed the production, coordinated communications and led the technical production.',
    'mkt.action2.1':      'Developed show concept and run-of-show',
    'mkt.action2.2':      'Coordinated technical requirements with the venue',
    'mkt.action2.3':      'Hosted and directed the live show',
    'mkt.action2.4':      'Managed communications and social media around the event',
    'mkt.result2':        'Successful live show in front of a live audience. Media coverage on multimedia-award.ch.',
    'mkt.cta':            'Interested in my work?',
    'mkt.btn-mail':       'Write me',

    /* --- ON --- */
    'on.heading':      'Letter of Motivation',
    'on.salutation':   'Dear ON Team',
    'on.p1':           'ON ignites the human spirit through movement. My work begins where a brand stops talking and starts making an impact.',
    'on.p2':           'I don\'t just bring experience &ndash; I also bring a well-founded perspective on ON as a brand. In my bachelor\'s thesis, I analysed the brand activism communication strategies of ON, Nike and Adidas, and came to understand what sets ON apart: authenticity that lives in the DNA, not stuck on the campaign surface.',
    'on.p3':           'What draws me to ON is precisely this ambition. <em>Ignite the human spirit through movement</em> doesn\'t exhaust itself in a trade show tent. It demands formats that trigger something, experiences that reach beyond the moment and truly move people. That\'s the standard I hold my own work to.',
    'on.p4':           'At Tit-Pit, I led brand experiences for brands like Migros across 10+ music festivals throughout Switzerland &ndash; from strategic concept and quoting through client alignment to on-site execution. In parallel, I managed content marketing and social media around these formats, because for me an event only truly works when it lives on beyond the moment and strengthens the brand.',
    'on.p5':           'This combination of campaign management, stakeholder ownership and operational precision is my sweet spot &ndash; and a perfect match for what ON does in the brand experience space.',
    'on.p6':           'I bring ownership, pace and a solutions-oriented mindset, and I believe the strongest experiences are created when genuine enthusiasm meets strategic thinking.',
    'on.closing':      'Keep moving,<br>Shayna Jucker',
    'on.lang-german':    'German',
    'on.lang-english':   'English',
    'on.skills-heading': 'skills',
    'on.skills-sub':     'Languages | Abilities | Programs | Architecture',
    'on.cat-languages':  'Languages',
    'on.cat-abilities':  'Abilities',
    'on.cat-programs':   'Programs',
    'on.cat-architecture': 'Architecture',
    'on.cert-heading': 'certificates',
    'on.cert-sub':     'CERTIFICATES &amp; GRADES',
    'on.cert-btn':     'Employment References &amp; Transcripts',

    /* --- Bachelor --- */
    'bach.thesis-heading': 'Thesis',
    'bach.thesis-sub':     'All about Bachelor Thesis',
    'bach.thesis-intro':   'Introduction',
    'bach.thesis-abs':     'Abstract',
    'bach.thesis-text':    'Brand Activism has established itself as a marketing strategy in which companies take a stand on social issues. In the sports industry, this concept is gaining increasing importance, particularly with regard to Generation Z.',
    'bach.proj-heading':   'Project',
    'bach.proj-sub':       'All about Bachelor Project',
    'bach.proj-text':      'As part of the bachelor project, a comprehensive corporate identity and corporate design (CICD) was developed for a construction consulting firm.',
    /* --- Tiny Miracles --- */
    'tm.role':         'Promotion Coordinator 100% &middot; Zurich Oerlikon',
    'tm.heading':      'Letter of Motivation',
    'tm.salutation':   'Dear Tiny Miracles Team',
    'tm.p1':           'When 40,000 people are standing in a field and the evening runs, someone kept a list for weeks beforehand. I know that role &ndash; I have held it at more than ten Swiss music festivals over the past year and a half.',
    'tm.p2':           'At TIT-PIT I am responsible for Migros brand experiences at festivals such as <strong>Frauenfeld</strong>, <strong>Pal&eacute;o</strong>, <strong>Gampel</strong>, <strong>Heitere</strong>, <strong>Moon &amp; Stars</strong> and <strong>Summerdays</strong> &ndash; from the first briefing through quoting and concept to on-site execution. I coordinate teams, hold timings, look after clients and stand on the ground at six in the morning on build day. What your ad lists under coordination, volunteers and presence at shows is my everyday work.',
    'tm.p3':           'The second half of this role is language. German and English are both mother tongues for me &ndash; my mother is American. At TIT-PIT I own social media content and client communication. Writing and editing press releases, newsletters, show announcements and presale landing pages in both languages is not an add-on for me &ndash; it is the part of the work I enjoy most.',
    'tm.p4':           'Why Tiny Miracles? Because behind TAKK ab Entertainment are the shows people keep an evening free for a year in advance. I come from music, I play guitar, I have spent years on festival grounds &ndash; and I know how much invisible coordination sits between an announcement post and the moment the lights go down. Working in that environment is not a job change for me, it is the logical next step.',
    'tm.p5':           'The role as central coordination point between CEO, Promotion Manager and team suits me. I work in a structured way, take ownership without a second loop of questions, and stay calm when something goes sideways two hours before doors. I welcome feedback &ndash; and I give it just as readily.',
    'tm.p6':           'One point where I want to be honest: I do not bring French. Everything else in your requirements profile I do bring &ndash; and I would take French on if the role calls for it.',
    'tm.closing':      'I look forward to meeting you.<br>Shayna Jucker',
    'tm.match-heading':'match',
    'tm.match-sub':    'Your job ad, point by point',
    'tm.m1-label':     'Supporting promotion campaigns',
    'tm.m1-text':      '10+ festival activations per year &ndash; briefings, timelines, follow-ups and coordination with external partners and suppliers.',
    'tm.m2-label':     'Drafting communication materials',
    'tm.m2-text':      'Social media and client communication at TIT-PIT. German and English mother tongue, both at publishing level in writing.',
    'tm.m3-label':     'Volunteers &amp; activation teams',
    'tm.m3-text':      'Scheduling and leading activation crews at festivals: shifts, briefings, resupply and quality on site.',
    'tm.m4-label':     'Presence at shows',
    'tm.m4-text':      'On site every summer: build-up, operation and teardown at more than ten festivals.',
    'tm.m5-label':     'Accreditations &amp; photographers',
    'tm.m5-text':      'Experience with media partners, photographers and guest management on festival grounds.',
    'tm.m6-label':     'Online advertising campaigns',
    'tm.m6-text':      'Content marketing and social ads around festival appearances. Adobe Creative Suite, Figma and Canva in daily use.',
    'tm.m7-label':     'Presentations &amp; reports',
    'tm.m7-text':      'Quotes, concepts and post-event reports with KPIs for clients such as Migros. MS Office in daily use.',
    'tm.m8-label':     'Coordination point in the team',
    'tm.m8-text':      'At TIT-PIT the interface between client, creation, production and crew &ndash; the role where information comes together.',
    'tm.facts-label':  'Key facts',
    'tm.fact1':        'Available from November 2026',
    'tm.fact2':        '100% &ndash; based in Pf&auml;ffikon ZH, about 25 minutes to Zurich Oerlikon',
    'tm.fact3':        'German and English mother tongue, no French',
    'tm.fact4':        'BSc Multimedia Production FHGR, specialisation Live Communication',
    'tm.fact5':        'Bachelor thesis: brand activism at ON, Nike and Adidas',
    'tm.skills-heading':'skills',
    'tm.skills-sub':   'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'tm.cert-heading': 'documents',
    'tm.cert-sub':     'CV, EMPLOYMENT REFERENCES &amp; TRANSCRIPTS',
    'tm.cv-btn':       'Curriculum Vitae',
    'tm.cert-btn':     'Employment References &amp; Transcripts',
    'tm.contact-cta':  'Questions? I am reachable directly.',
    'tm.btn-mail':     'Write me',

    /* --- Hallo (general application) --- */
    'app.heading':     'Hello.',
    'app.lead':        'I build brand experiences that work beyond the day of the event.',
    'app.p1':          'I am Shayna Jucker, 28, based in Pf&auml;ffikon ZH. At TIT-PIT I am responsible for Migros brand experiences at more than ten Swiss music festivals &ndash; from the first briefing to the last truck leaving the ground.',
    'app.p2':          'I started somewhere else: five years as an architectural drafter, then a degree in Multimedia Production with a specialisation in Live Communication. That combination explains how I work. I read a stand plan like a drafter, think the brand like a strategist and stand on site at six in the morning on build day.',
    'app.p3':          'This page is not an application for one specific job. It shows what people hire me for &ndash; and how I work when things get tight.',
    'app.roles-heading':'roles',
    'app.roles-sub':   'What people hire me for',
    'app.label-proof': 'Evidence',
    'app.label-role':  'My Role',
    'app.label-actions':'In practice',
    'app.r1-title':    'Brand Experience &amp; Live Events',
    'app.r1-sub':      'Brand appearances that work on site and live on afterwards',
    'app.r1-proof':    '10+ major Swiss festivals per year for Migros: Frauenfeld, Pal&eacute;o, Gampel, Heitere, Moon &amp; Stars, Stars in Town, Lumnezia, Luzern Live, Seaside, Summerdays and Summerstage.',
    'app.r1-role':     'Project Manager | Marketing, Events &amp; Brand Experience, TIT-PIT GmbH &ndash; with full client ownership.',
    'app.r1-a1':       'Concepts and quotes for activations, aligned directly with the client',
    'app.r1-a2':       'Coordinating suppliers, build teams and crews',
    'app.r1-a3':       'Merci Bus Tour for the 100th anniversary of Migros (2025)',
    'app.r1-a4':       'Lead on the Mocktail Bar Tour 2026',
    'app.r1-a5':       'On-site project leadership: build-up, operation, teardown, quality assurance',
    'app.r2-title':    'Campaigns, Content &amp; Communication',
    'app.r2-sub':      'Copy, image and channel so the brand is stronger afterwards than before',
    'app.r2-proof':    'German and English mother tongue. Radio reporter at Radio S&uuml;dostschweiz, social media and graphic design at TIT-PIT, multimedia design at fliggs mobile.',
    'app.r2-role':     'Responsible for content, design and client communication &ndash; from the idea to the published piece.',
    'app.r2-a1':       'Social media content and editorial planning around live formats',
    'app.r2-a2':       'Design and layout with Adobe Creative Suite, Figma and Canva',
    'app.r2-a3':       'Client communication and a consistent brand voice across all touchpoints',
    'app.r2-a4':       'Research, production and presenting on radio',
    'app.r2-a5':       'Bachelor thesis on brand activism at ON, Nike and Adidas',
    'app.r3-title':    'Project Management &amp; Coordination',
    'app.r3-sub':      'The place in the team where information comes together',
    'app.r3-proof':    'In project ownership roles continuously since 2020 &ndash; first in architecture, today in live marketing.',
    'app.r3-role':     'Interface between client, creation, production and crew. Decide, prioritise, follow up.',
    'app.r3-a1':       'Full client ownership from briefing to final report',
    'app.r3-a2':       'Budget responsibility and quoting',
    'app.r3-a3':       'Leading cross-functional teams, including without formal authority',
    'app.r3-a4':       'Scheduling and sequencing across several parallel projects',
    'app.r3-a5':       'Trusted with independent project leadership within 1.5 years',
    'app.how-heading': 'principles',
    'app.how-sub':     'How I work',
    'app.h1-label':    'Understand first, promise second',
    'app.h1-text':     'I would rather tell a client in the briefing that something will not work than on build day. It takes courage once and saves money three times.',
    'app.h2-label':    'The event is not the goal',
    'app.h2-text':     'An appearance only works for me when it lives on beyond the moment. That is why I plan content in from the start, not as an afterthought.',
    'app.h3-label':    'Staying calm is a skill',
    'app.h3-text':     'Two hours before doors, something regularly goes sideways. Whoever sets priorities then instead of debating saves the evening.',
    'app.h4-label':    'Being able to read plans helps',
    'app.h4-text':     'Five years of architecture mean I can tell from a stand plan whether an idea can be built &ndash; before anyone quotes it.',
    'app.facts-label': 'In numbers',
    'app.fact1':       '10+ major Swiss festivals per year under my own responsibility',
    'app.fact2':       '2 mother tongues: German and English',
    'app.fact3':       '5 years of architecture: ArchiCAD, Vectorworks, 3D visualisation',
    'app.fact4':       '1 semester abroad in Transmedia Design in Tilburg, Netherlands',
    'app.fact5':       '100 years of Migros: Merci Bus Tour 2025',
    'app.skills-heading':'skills',
    'app.skills-sub':  'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'app.cert-heading':'documents',
    'app.cert-sub':    'CV, EMPLOYMENT REFERENCES &amp; TRANSCRIPTS',
    'app.cv-btn':      'Curriculum Vitae',
    'app.cert-btn':    'Employment References &amp; Transcripts',
    'app.cases-btn':   'View cases',
    'app.contact-cta': 'Does this fit a role at your company?',
    'app.btn-mail':    'Write me',
    'app.btn-linkedin':'LinkedIn',

    /* --- General application --- */
    'bw.role':         'Marketing &middot; Events &middot; Brand Experience',
    'bw.heading':      'Letter of Motivation',
    'bw.salutation':   'Dear Team',
    'bw.p1':           'When 40,000 people are standing in a field and the evening runs, someone kept a list for weeks beforehand. I know that role &ndash; I have held it at more than ten Swiss music festivals over the past year and a half. My work begins where a brand stops talking and starts making an impact.',
    'bw.p2':           'At TIT-PIT I am responsible for Migros brand experiences at festivals such as <strong>Frauenfeld</strong>, <strong>Pal&eacute;o</strong>, <strong>Gampel</strong>, <strong>Heitere</strong>, <strong>Moon &amp; Stars</strong> and <strong>Summerdays</strong>. From the first briefing through concept and budget to on-site execution. I develop how the brand shows up on the ground and what it says there, coordinate teams and suppliers, and hold timings and budgets. And I stand on site at six in the morning on build day, because I want to see whether the idea actually holds.',
    'bw.p2b':          'So far I have done all of that from the agency side, on someone else&rsquo;s behalf. Now I would like to move to the other side: to shape a brand from within instead of staging it for others. What I bring with me is experience from both ends of the briefing. I know how an agency thinks and calculates, and what it needs in order to deliver good work.',
    'bw.p3':           'German and English are both mother tongues for me. My mother is American. At TIT-PIT I own social media content and client communication around these formats, because for me an event only truly works when it lives on beyond the moment and strengthens the brand. Writing and editing concepts and copy in both languages is not an add-on for me &ndash; it is the part of the work I enjoy most.',
    'bw.p4':           'I started somewhere else. Five years as a draughtswoman in architecture, then project management, then a BSc in Multimedia Production with a specialisation in Live Communication and an exchange semester in the Netherlands. In my bachelor&rsquo;s thesis I analysed the brand activism communication strategies of ON, Nike and Adidas. Authenticity lives in a brand&rsquo;s DNA, it is not stuck on the campaign surface. That combination explains how I work. I read a stand layout like a draughtswoman, think about the brand like a strategist, and keep an eye on both when things get tight.',
    'bw.p5':           'This combination of campaign management, stakeholder ownership and operational precision is my sweet spot. I work in a structured way, take ownership without a second loop of questions, and stay calm when something goes sideways two hours before doors. I bring pace and a solutions-oriented mindset, and I value a direct line to the team and to the people I work with.',
    'bw.p6':           'What I am looking for is a role in the marketing or brand team of a company that runs its own brand. Events, campaign, brand presence and content belong together for me. What appeals to me is thinking a brand through across a season, rather than building it up for one weekend and taking it down again. Because a brand promise does not exhaust itself in a trade show tent. It takes formats that trigger something and genuinely move people.',
    'bw.closing':      'I believe the strongest experiences are created when genuine enthusiasm meets strategic thinking. Happy to discuss everything else in person. I look forward to meeting you.<br>Shayna Jucker',
    'bw.skills-heading':'skills',
    'bw.skills-sub':   'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'bw.cert-heading': 'documents',
    'bw.cert-sub':     'CV, EMPLOYMENT REFERENCES &amp; TRANSCRIPTS',
    'bw.cv-btn':       'Curriculum Vitae',
    'bw.cert-btn':     'Employment References &amp; Transcripts',
    'bw.contact-cta':  'Questions? I am directly reachable.',
    'bw.btn-mail':     'Write me',

    /* --- Presale work sample --- */
    'ps.eyebrow':      'Work sample for Tiny Miracles Communication AG',
    'ps.heading':      'Presale Landing Page',
    'ps.lead':         'Your ad says &ldquo;presale landing pages&rdquo;. Instead of writing that I can do it, I built one.',
    'ps.p1':           'A presale page has exactly one job: between the announcement and the on-sale, no question should be left open that would otherwise land in the info inbox. Every question the page answers is an email nobody has to write.',
    'ps.p2':           'So it is not ordered by aesthetics but by the order people think in: When? How do I get the code? What does it cost? Am I allowed in? And, as a journalist: who is my contact?',
    'ps.p3':           'The countdown knows four states &ndash; before the presale, during the presale, between presale and general sale, and after. A page still showing &ldquo;starts in 0 days&rdquo; on sale day costs trust. Details like that decide whether an announcement runs cleanly or generates support.',
    'ps.p4':           'Technically it is a single HTML file: no framework, no build tools, no external requests. For the next show you swap eight values &ndash; act, tour, date, venue, three sale timestamps, prices. German and English are built in.',
    'ps.btn-demo':     'Open the landing page',
    'ps.btn-pr':       'Press release DE / EN',
    'ps.does-heading': 'details',
    'ps.does-sub':     'What the page does',
    'ps.d1-label':     'Every date in one place',
    'ps.d1-text':      'Code send-out, presale window and general sale are on the page with date and time. Those are the three questions that otherwise arrive one by one by email.',
    'ps.d2-label':     'Four countdown states',
    'ps.d2-text':      'The page stays correct even if nobody touches it on sale day. Once tickets are on open sale the counter removes itself.',
    'ps.d3-label':     'Bilingual out of the box',
    'ps.d3-text':      'German and English live in the same file, switchable with one click. No second template, no second thing to maintain.',
    'ps.d4-label':     'Accreditation answered up front',
    'ps.d4-text':      'Deadline, pit rules and contact are on the page. That removes a stack of individual requests before every show.',
    'ps.d5-label':     'Accessibility and resale answered',
    'ps.d5-text':      'Wheelchair spaces, companion tickets and the secondary market are the two topics that reliably reach the inbox. Both are covered in the FAQ.',
    'ps.d6-label':     'One file, no dependencies',
    'ps.d6-text':      'Runs on any hosting, loads nothing from outside and is adapted to the next show in about ten minutes.',
    'ps.honest-label': 'For the record',
    'ps.honest1':      'Luma Rivers, Nils Bregenz, the date and the prices are invented',
    'ps.honest2':      'Not official material from any promoter, no reference to a real planned show',
    'ps.honest3':      'The press contact is deliberately my own address',
    'ps.honest4':      'The newsletter field is intentionally disabled &ndash; a work sample does not collect addresses',
    'ps.honest5':      'Built over a weekend, in under a day',
    'ps.pr-heading':   'press release',
    'ps.pr-sub':       'Show announcement for the same show',
    'ps.pr-text':      'The press release belongs with the landing page because in practice both go out the same morning. German and English, in the usual structure: embargo, dateline, lead answering the basic questions, quote, ticketing block, boilerplate and media contact. It doubles as my writing sample in both languages.',
    'ps.btn-pr2':      'Press release DE / EN',
    'ps.btn-back':     'Back to the application',
    'ps.contact-cta':  'Questions about the work sample? Directly, please.',
    'ps.btn-mail':     'Write me',
    'tm.sample-heading':'work sample',
    'tm.sample-sub':   'Not a claim &ndash; the work itself',
    'tm.sample-text':  'Your ad lists &ldquo;presale landing pages&rdquo; as a task. So I built one &ndash; with a countdown across four sale states, FAQ, accreditation rules, German and English, as a single file with no dependencies. Plus the matching press release in both languages. The show in it is invented; the mechanics are real.',
    'tm.sample-btn':   'See the work sample',

    /* --- Application Zweifel Weine & Getränke --- */
    'zw.role':          'Marketing &amp; Design &middot; Zweifel Weine &amp; Getr&auml;nke group',
    'zw.heading':       'Letter of Motivation',
    'zw.salutation':    'Dear Mr Frischknecht',
    'zw.p1':            'A new wine joins the range. It needs a shelf talker, a tasting card, a sales sheet for restaurants and a post. Four materials, the same details typed four times, four chances for the vintage or the price to drift apart. Instead of writing to you that I can do this, I built it: a kit that turns a single data entry into all four materials, print-ready. It is further down this page.',
    'zw.p2':            'At TIT-PIT I am responsible for Migros&rsquo; brand experiences at more than ten Swiss music festivals &ndash; <strong>Frauenfeld</strong>, <strong>Pal&eacute;o</strong>, <strong>Gampel</strong>, <strong>Heitere</strong>, <strong>Moon &amp; Stars</strong>, <strong>Summerdays</strong>. From the first briefing through concept, quote and budget to delivery on site. Plus everything attached to it: designing the materials, social media content, client communication, coordinating suppliers and productions. I am the point where brand, production and budget meet &ndash; and I am on the ground at six on build-up day, because I want to see whether the idea actually holds.',
    'zw.p3':            'My connection to drinks is not theoretical: in 2026 I am leading the <strong>Mocktail Bar Tour</strong> for Migros &ndash; drinks, service and brand presence at changing locations, with everything that comes with it: explaining the product, briefing staff, securing supply, producing the imagery.',
    'zw.p5':            'I studied Multimedia Production at FHGR with a specialisation in Live Communication. In my bachelor thesis I analysed the brand activism strategies of ON, Nike and Adidas. What I took from it I use daily: a brand does not convince where it is loudest, but where it does the same thing for years.',
    'zw.p6':            'On AI tools, since your job posting names them explicitly: I work with them daily &ndash; for drafts and copy variants, for concept ideas and above all in image editing, from cutting out and retouching to adapting formats for the different channels. I believe in these tools. They do not take the work away, they take away the idle time: what used to be half a day of manual work is now fifteen minutes &ndash; and the time gained goes where it counts, into the idea behind it. You should work with them rather than fear them. Anyone who masters them tries out more and arrives at better results.',
    'zw.p7':            'Why Zweifel? Honestly: I have known the name for as long as I can remember &ndash; as a child from the crisp packet, though, not from the wine list. That those crisps once came out of the cider mill in H&ouml;ngg, and therefore out of the same house that started with wine and beverages in 1898, I only learned later. And these days I like the wines just as much, of course. That long root is exactly what draws me: a brand that is not built up for one weekend and taken down again, but one that has been growing for over 125 years. That is what I want to help build.',
    'zw.closing':       'Everything else gladly in person.<br>Kind regards<br>Shayna Jucker',
    'zw.sample-heading':'work sample',
    'zw.sample-sub':    'Not a claim &ndash; the work itself',
    'zw.sample-p1':     '<strong>&ldquo;Weinblatt&rdquo; &ndash; one wine, four materials, one layout system.</strong> Type the wine data once and the shelf talker, tasting card, gastronomy sales sheet and social tile are built at the same time. Every material prints at its real final size: 55&times;105 mm, A6 landscape, A5. The social tile downloads as an SVG and opens straight in Illustrator.',
    'zw.sample-p2':     'Three things about it matter more to me than the looks. <strong>First:</strong> the accent changes with the wine category while grid and typography stay &ndash; so the corporate design is anchored in the system, not in the discipline of whoever happens to have time. <strong>Second:</strong> the same wine is told in three registers &ndash; terse on the shelf, technical in a trade meeting, relaxed on social. That is writing, not formatting. <strong>Third:</strong> the sales sheet calculates the recommended bottle and by-the-glass price from the trade price and the markup factor. That is the number restaurants ask about first.',
    'zw.sample-p3':     'Every wine, price and award in it is invented, the wordmark is a placeholder, and it is not official material of your house. Technically it is a single HTML file: no framework, no external requests, no data collection. Bilingual German and English. Built over a weekend.',
    'zw.sample-btn':    'Open the kit',
    'zw.cases-btn':     'See marketing cases',
    'zw.match-heading': 'match',
    'zw.match-sub':     'Your job posting, point by point',
    'zw.m1-label':      'Developing the brand',
    'zw.m1-text':       'Brand management and brand experience daily for the past year and a half &ndash; designing brand appearances and keeping them consistent across a whole season.',
    'zw.m2-label':      'Corporate identity across all channels',
    'zw.m2-text':       'At TIT-PIT I am responsible for our own brand presence across every touchpoint. My work sample shows how I anchor CI systematically instead of policing it.',
    'zw.m3-label':      'Print, digital and POS',
    'zw.m3-text':       'From stand layout and signage through flyers and sales documents to social assets. Artwork and print-ready files included &ndash; that comes from five years of architectural drafting.',
    'zw.m4-label':      'Visual concepts for campaigns',
    'zw.m4-text':       'Concepts for Migros activations at more than ten festivals: idea, imagery, mechanics and delivery, each from first briefing to breakdown.',
    'zw.m5-label':      'Planning and running campaigns',
    'zw.m5-text':       'Campaign management with timeline, budget, suppliers and reporting. Post-event reports with KPIs for clients are standard.',
    'zw.m6-label':      'Content for social, newsletter, website',
    'zw.m6-text':       'Responsible for social media content and client communication at TIT-PIT. German and English both native, both written to publication standard.',
    'zw.m7-label':      'Every document produced independently',
    'zw.m7-text':       'Adobe Creative Cloud daily: InDesign, Illustrator, Photoshop, Premiere Pro, After Effects, Lightroom. Plus Figma, Canva and websites. I do not need an agency for a sales sheet.',
    'zw.m8-label':      'AI tools in the content process',
    'zw.m8-text':       'In daily use for drafts, variants and image preparation &ndash; with a clear line: the draft may come from the tool, the text that goes out is edited.',
    'zw.m9-label':      'Sales documents &amp; wine marketing',
    'zw.m9-text':       'Quotes, concepts and sales documents for clients such as Migros. How I build trade and retail material is exactly what the kit shows, margin calculator included.',
    'zw.m10-label':     'Supplier campaigns',
    'zw.m10-text':      'Running campaigns with external partners and their guidelines is agency routine: respect someone else&rsquo;s rules and still hold your own brand.',
    'zw.m11-label':     'Tastings, trade fairs, customer events',
    'zw.m11-text':      'Live communication is my degree specialisation and my job: more than ten major events a year, plus hosting and directing the Multimedia Award 2023 at Plaza Zurich.',
    'zw.m12-label':     'Projects, agencies, budget',
    'zw.m12-text':      'Project management since 2020, first in architecture, now in marketing. Budget responsibility, production coordination and agency and supplier steering from both sides of the briefing.',
    'zw.facts-label':   'Key facts &ndash; including the awkward ones',
    'zw.fact1':         'Available from November 2026',
    'zw.fact2':         'Based in Pf&auml;ffikon ZH &ndash; about 15 minutes to Volketswil, about 30 to Zurich-H&ouml;ngg',
    'zw.fact3':         'German and English native &ndash; I do not speak Italian',
    'zw.fact4':         'No professional experience in the wine and beverage trade, but experience with drinks activations and serving at public events',
    'zw.fact5':         'Qualified architectural draftswoman &ndash; five years of artwork and dimensional accuracy',
    'zw.fact6':         'BSc Multimedia Production FHGR, specialisation Live Communication, exchange semester in the Netherlands',
    'zw.fact7':         'Bachelor thesis: brand activism at ON, Nike and Adidas',
    'zw.skills-heading':'skills',
    'zw.skills-sub':    'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
    'zw.cert-heading':  'documents',
    'zw.cert-sub':      'CV, REFERENCES &amp; ACADEMIC RECORDS',
    'zw.cv-btn':        'CV',
    'zw.cert-btn':      'References &amp; academic records',
    'zw.contact-cta':   'Questions? I am reachable directly.',
    'zw.btn-mail':      'Write me',

    /* --- ON Brand & Event Marketing Manager --- */
    'obe.role':          'Brand &amp; Event Marketing Manager &middot; ON',
    'obe.heading':       'Letter of motivation',
    'obe.salutation':    'Dear ON Team',
    'obe.p1':            'ON ignites the human spirit through movement. My work begins where a brand stops talking and starts making an impact.',
    'obe.p1b':           'Instead of writing to you that I think brand and delivery together, I have shown it: <strong>&ldquo;Elevation&rdquo;</strong> &ndash; a campaign concept for ON in three key visuals. It is further down this page.',
    'obe.p2':            'I don\'t just bring experience &ndash; I also bring a well-founded perspective on ON as a brand. In my bachelor\'s thesis, I analysed the brand activism communication strategies of ON, Nike and Adidas, and came to understand what sets ON apart: authenticity that lives in the DNA, not stuck on the campaign surface.',
    'obe.p3':            'What draws me to ON is precisely this ambition. <em>Ignite the human spirit through movement</em> doesn\'t exhaust itself in a trade show tent. It demands formats that trigger something, experiences that reach beyond the moment and truly move people. That\'s the standard I hold my own work to.',
    'obe.p4':            'At Tit-Pit, I led brand experiences for brands like Migros across 10+ music festivals throughout Switzerland &ndash; from strategic concept and quoting through client alignment to on-site execution. In parallel, I managed content marketing and social media around these formats, because for me an event only truly works when it lives on beyond the moment and strengthens the brand.',
    'obe.p5':            'This combination of campaign management, stakeholder ownership and operational precision is my sweet spot &ndash; and a perfect match for what ON does in the brand experience space.',
    'obe.p6':            'I bring ownership, pace and a solutions-oriented mindset, and I believe the strongest experiences are created when genuine enthusiasm meets strategic thinking.',
    'obe.p7':            'Why ON? Honestly: I once took this brand apart for half a year &ndash; for my bachelor\'s thesis, from the outside, with a bibliography. What I was left with was not just a grade but a sympathy I had not planned for: a Swiss brand that started in a workshop and today runs worldwide without ever getting loud about it. That is exactly what appeals to me &ndash; after a year and a half in an agency, playing other people\'s brands, I want to build one from the inside. This one.',
    'obe.closing':       'Happy to tell you the rest in person.<br>Keep moving,<br>Shayna Jucker',
    'obe.cert-heading':  'documents',
    'obe.cert-sub':      'CV, REFERENCES &amp; ACADEMIC RECORDS',
    'obe.cv-btn':        'CV',
    'obe.cert-btn':      'References &amp; academic records',
    'obe.contact-cta':   'Questions? I am reachable directly.',
    'obe.btn-mail':      'Write me',
    'obe.sample-heading':'work sample',
    'obe.sample-sub':    'Instead of a claim: the work itself',
    'obe.sample-p1':     '<strong>&ldquo;Elevation&rdquo;</strong> &ndash; a campaign concept for ON in three key visuals. The contour line of the Swiss national map as a visual language: every motif is a route, drawn like a map, carrying its elevation profile as a signature. Idea, claim, headlines and design by me &ndash; fictional, but built as a system that translates to any terrain and any format.',
    'obe.sample-btn':    'See the campaign',
    'obe.match-heading': 'match',
    'obe.match-sub':     'The role, point by point',
    'obe.m1-label':      'Designing brand experiences',
    'obe.m1-text':       'Daily for the past year and a half: brand presences for Migros at more than ten Swiss festivals &ndash; Frauenfeld, Pal&eacute;o, Gampel, Heitere, Moon &amp; Stars, Summerdays. Idea, imagery, mechanics, delivery.',
    'obe.m2-label':      'Running events end to end',
    'obe.m2-text':       'From first briefing through quote, floor plan and supplier coordination to breakdown. I am on site at six on build day, because I want to see whether the idea actually holds up.',
    'obe.m3-label':      'Making formats scalable',
    'obe.m3-text':       'One system, many applications: my work sample shows a visual language that stays the same across terrain, languages and formats &ndash; exactly what it takes when the same image has to work in fifteen markets.',
    'obe.m4-label':      'Holding the brand standard',
    'obe.m4-text':       'At TIT-PIT I am responsible for our own brand presence across every touchpoint. I anchor CI in the system instead of policing it &ndash; the only approach that survives a full season.',
    'obe.m5-label':      'Budget and timeline',
    'obe.m5-text':       'Budget ownership per project, quotes, final costing and post-event reports with KPIs for the client. Cost per contact is not a theoretical figure for me.',
    'obe.m6-label':      'Steering agencies and partners',
    'obe.m6-text':       'I know both sides of the briefing. From the agency side I know what a good brief sets off, where the buffers are hidden and how to get a production through cleanly.',
    'obe.m7-label':      'Content around events',
    'obe.m7-text':       'Social media content and client communication around every format &ndash; because an event only works when it lives on beyond the moment. Photo, video, editing and copy I do myself.',
    'obe.m8-label':      'German and English',
    'obe.m8-text':       'Both native, my mother is American. I write and edit concepts, briefings and captions in both languages to publication standard &ndash; this page and the work sample are the proof.',
    'obe.m9-label':      'Community and retail',
    'obe.m9-text':       'In 2026 I am running the Mocktail Bar Tour for Migros: serving and brand presence at changing locations, with staff briefings, restocking and imagery. Return visits rather than reach is the metric there.',
    'obe.m10-label':     'Working cross-functionally',
    'obe.m10-text':      'Translating between client, creative, production and crew is my everyday work. Project management since 2020 &ndash; first in architecture, now in marketing.',
    'obe.m11-label':     'Being able to design it yourself',
    'obe.m11-text':      'Adobe Creative Cloud daily: InDesign, Illustrator, Photoshop, Premiere Pro, After Effects, Lightroom. Plus Figma, Canva and websites. I do not need an agency for a floor plan or a briefing.',
    'obe.m12-label':     'AI tools in the process',
    'obe.m12-text':      'In daily use for drafts, variants and image preparation &ndash; with a clear line: the draft may come from the tool, the text that goes out is edited. This campaign was built that way too.',
    'obe.facts-label':   'Key facts &ndash; including the awkward ones',
    'obe.fact1':         'Available from November 2026',
    'obe.fact2':         'Based in Pf&auml;ffikon ZH &ndash; about 30 minutes to Zurich',
    'obe.fact3':         'German and English native',
    'obe.fact4':         'No professional experience in the sporting goods industry &ndash; but more than ten major events a year, from concept to breakdown',
    'obe.fact5':         'Qualified architectural draftswoman &ndash; five years of artwork and dimensional accuracy',
    'obe.fact6':         'BSc Multimedia Production FHGR, specialisation Live Communication, exchange semester in the Netherlands',
    'obe.fact7':         'Bachelor thesis: brand activism at ON, Nike and Adidas',
    'obe.skills-heading':'skills',
    'obe.skills-sub':    'Management &middot; Events &middot; Marketing &middot; Design &middot; Tools &middot; Architecture',
  }
};

(function () {
  var STORAGE_KEY = 'sj_lang';

  function getCurrentLang() {
    return localStorage.getItem(STORAGE_KEY) || 'de';
  }

  function applyLang(lang) {
    var dict = window.SJ_LANG[lang];
    if (!dict) return;

    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (dict[key] !== undefined) {
        el.innerHTML = dict[key];
      }
    });

    /* Update skill-item hover labels */
    document.querySelectorAll('[data-level-de][data-level-en]').forEach(function (el) {
      el.setAttribute('data-level', el.getAttribute('data-level-' + lang));
    });

    /* Update toggle button label */
    var btn = document.getElementById('lang-toggle');
    if (btn) btn.textContent = lang === 'de' ? 'EN' : 'DE';

    /* Update html lang attribute */
    document.documentElement.lang = lang;
  }

  window.SJ_toggleLang = function () {
    var next = getCurrentLang() === 'de' ? 'en' : 'de';
    localStorage.setItem(STORAGE_KEY, next);
    applyLang(next);
  };

  /* Apply on load */
  document.addEventListener('DOMContentLoaded', function () {
    applyLang(getCurrentLang());
  });
})();
